### ISSUE TITLE
Sequence all in one doesnt support lifelines through inner frames

### ISSUE THREAD

**Issue by GoogleCodeExporter** [umlet/umlet#1]
```
It's not possible to create lifelines which go through inner frames. Inner 
frames always cut them in 2 lifelines

The attached seq1.uxf should look like seq3.uxf

What version of the product are you using? On what operating system?
10.4

```

Original issue reported on code.google.com by `AFDiaX` on 19 Dec 2010 at 10:24

Attachments:
* [seq1.uxf](https://storage.googleapis.com/google-code-attachments/umlet/issue-1/comment-0/seq1.uxf)
* [seq3.uxf](https://storage.googleapis.com/google-code-attachments/umlet/issue-1/comment-0/seq3.uxf)

**Comment by afdia** [comment]
resolved in new sequence AIO diagram
