### ISSUE TITLE
Provide a "Link" to navigate from one diagram to another

### ISSUE THREAD

**Issue by GoogleCodeExporter** [umlet/umlet#122]
```
What version of the product are you using? 11.5
On what operating system? Windows 7


Please provide any additional information below.

Connecting diagrams will make it easier to create multilevel designs without 
the hassle of finding the files.  We just would need to open the main design 
and navigate to the related designs.

Thank you.


```

Original issue reported on code.google.com by `diego.ri...@hcss.com` on 16 Feb 2013 at 1:48

**Comment by smbody** [comment]
+1 my vote for this issue

**Comment by ubaldy** [comment]
+1 my vote, UMLet is amazing and this is my only current critique

**Comment by matelakat** [comment]
+1 is my vote here, would love to have this!

**Comment by barthel** [comment]
+1 my vote too

**Comment by GJFenn** [comment]
Hi UMLet,

Would it be possible to have a feature where you can assign a filename as a "link" to a UML element e.g. a class, as a property of that class such thatdouble-clicking it will open a .uxf file with that name? For example, it could be as simple as the following:

- For a class or use-case, the Properties box accepts <linkto="SimpleClass.uxf"> or <linkto="../../OtherSubproject/MyUseCaseDiagram/uxf">
- with this, a double-click on the item will call ajava function to load that .uxf file (if it exists) into a new UMLet tab, and opens that tab up.

I might be missing some steps, but on the surface it feels like a very easy feature to implement and would make the tool much better for with several classes. For example I like to make games in Unity as a hobby and need seperate diagrams to describe each mechanic (Input, Audio, ItemSelection, UserState, Map, SaverAndLoader, WeatherSystem, etc). It would be messy to have these in a large diagram. It would be better to have a small class A described on one diagram which depends on or implements or generalises another class B, with the detailed design for B in another .uxf file which can be quickly navigated to.

**Comment by afdia** [comment]
Links will be possible in standalone Umlet using a link= property to define them and a context menu to navigate to them (see #743)
