### ISSUE TITLE
Umlet very slow on java 8

### ISSUE THREAD

**Issue by GoogleCodeExporter** [umlet/umlet#177]
```
With the new instalation of java(jdk 8), and with show grid option turned on 
application is painfuly slow. Typing text lags a lot, and entire application 
turn almost imposible to use. Retrieving java to jdk1.7.0_51 removes this. 

Operating system is Ubuntu Linux 12.04 x64.


```

Original issue reported on code.google.com by `cvetan.s...@gmail.com` on 13 Apr 2014 at 2:55

**Comment by afdia** [comment]
closed as unfortunately this cannot be fixed in the application code

**Comment by afdia** [comment]
As mentioned in in #275, the issue seems to be located in Java.

As a workaround, append " -Dsun.java2d.xrender=false " to the sh-script as seen in the change in #275:
https://github.com/SammysHP/umlet/commit/7eef69d8b828f757963eb55cb2596126ba06123e
