### ISSUE TITLE
specify multiple text colors in a single element

### ISSUE THREAD

**Issue by GoogleCodeExporter** [umlet/umlet#184]
```
What steps will reproduce the problem?
1. create an element
2. fill with multiple fg=....
3. text takes the last fg color mentioned

What is the expected output? What do you see instead?
Expected: was hoping to have the text color change part way through the element
Instead: text color takes the last fg declaration available

What version of the product are you using? On what operating system?
Mac 0sx 10.8.5 umlet v 12.0

Please provide any additional information below.
this isn't really an issue, I'm just wondering if there is a way that i have 
missed which would allow me to specify text color, especially if i could make 
inidividual words have there own color.

Thanks!

```

Original issue reported on code.google.com by `TJAur...@gmail.com` on 10 Jun 2014 at 9:34

**Comment by afdia** [comment]
sorry for the very late answer (I have missed this issue completely)
We have thought about applying several commands like fg=xxx starting with the line where the command is mentioned, but we've decided to keep the syntax as simple as possible and therefore only the last command will be used.

If we would apply fg=xx beginning with the line where it is first mentioned (and therefore make it overwritable), you would be forced to write it in the top line if you want to apply it to the whole content and this would be quite limiting (I guess most users "collect" commands like fg=xxx at the bottom of the properties)

But it's possible that we will change that behavior in the future for more flexible commands
