### ISSUE TITLE
Microsoft IME (Japanese) not work correctly on Umlet 13.0

### ISSUE THREAD

**Issue by GoogleCodeExporter** [umlet/umlet#206]
```
What steps will reproduce the problem?
1.Add UML Use Case "System" element to the diagram.
2.Type Japanese text on it Properties box.
3.Type "suteki" on the keyboard, in Japanese input mode.

What is the expected output? What do you see instead?
Expected:すてき
Instead:ｓすすｔすてすてｋすてきすてきすてき

What version of the product are you using? On what operating system?
Umlet 13.0, Windows 8.1.

Please provide any additional information below.
It works well on Umlet 12.2
When works correctly, "su" will create す, "te" will create て, "ki" create 
き.
```

Original issue reported on code.google.com by `umbalaco...@gmail.com` on 24 Oct 2014 at 7:35

**Comment by afdia** [comment]
The error was introduced in 04a2a3f2eabcb52ed6091226a16d0da9c7bc5ae3

**Comment by afdia** [comment]
reverted the change of 04a2a3f2eabcb52ed6091226a16d0da9c7bc5ae3 partially (the text part which is the source of the IME problems

switching between old and new class with same text works and highlighting works too, so it should be OK to revert the change
