### ISSUE TITLE
new elements with "style=autoresize" resize weird in tiny zoom levels

### ISSUE THREAD

**Issue by GoogleCodeExporter** [umlet/umlet#221]
```
What steps will reproduce the problem?
1. open attached diagram
2. zoom to 10% and back a few times

What is the expected output? What do you see instead?
Expected: diagram stays the same
Instead: the box size changes and therefore the arrows change too

```

Original issue reported on code.google.com by `AFDiaX` on 8 Jan 2015 at 6:05

Attachments:
* [StateChartTest.uxf](https://storage.googleapis.com/google-code-attachments/umlet/issue-221/comment-0/StateChartTest.uxf)

**Comment by afdia** [comment]
the fix for #229 also fixed this issue
