### ISSUE TITLE
Saved files as recent files

### ISSUE THREAD

**Issue by Xanhou** [umlet/umlet#246]
After saving a file, I would expect it to become a 'recent file', allowing quick loading via the menu. This is not the case in Umlet 11.3 .

**Comment by laughlinbarker** [comment]
Works fine in 13.2 for me.

**Comment by afdia** [comment]
Since v11.3 is quite outdated, please try again using 13.2, because I cannot reproduce it either
thanks

**Comment by Xanhou** [comment]
Ah. There is a much newer version!
The ubuntu repository contains 11.3
Will download the latest version directly then.

**Comment by Xanhou** [comment]
Annnd reverting back to 11.3 as it seems to be way more responsive to my actions...
