### ISSUE TITLE
Selection loss after dragging screen

### ISSUE THREAD

**Issue by laughlinbarker** [umlet/umlet#247]
If an element is selected, and I use "Shift+Mouse Drag" to navigate to a new portion of the document, my selection is gone. Win7, Umlet 13.2, JRE 1.60_02

**Comment by afdia** [comment]
what do you mean with "new portion of the document"?
if you drag the element itself, the selection should be retained, if you drag the whole diagram (by dragging the background), the selection will be lost because you have selected the whole diagram

**Comment by laughlinbarker** [comment]
Closing this issue as screen navigation can be achieved using Middle-mouse-click-drag per https://github.com/umlet/umlet/issues/248
