### ISSUE TITLE
Allow "fixed" element?

### ISSUE THREAD

**Issue by laughlinbarker** [umlet/umlet#248]
Enhancement request: Perhaps allow an element to be "fixed" relative to the background. For example, I might have a fixed square and colored element which defines a while loop, with a State Machine diagram inside it. If I Shift-click/drag inside this colored square element, I would want the whole diagram to scroll over, not the colored element itself.

**Comment by afdia** [comment]
Can you please add a screenshot or example diagram for this?

Perhaps you can get the desired behavior by using groups.
If you group 2 elements together and select one of it, the other one will automatically be selected and therefore always moved at the same time.

**Comment by laughlinbarker** [comment]
Here's an attempt at explanation. 

![bg_not fixed](https://cloud.githubusercontent.com/assets/3249523/6922436/f7468770-d77f-11e4-8cd3-f00c0b1824b4.PNG)
**Figure 1:** I have grouped the two large elements in layer -1 ("while(1)" and "State Machine"), and placed multiple elements on top. 

![bg_not_fixed2](https://cloud.githubusercontent.com/assets/3249523/6922437/f7482ae4-d77f-11e4-9e24-6f9cc9e9ee70.PNG)
**Figure 2:** In attempting to navigate to the left, I *Shift-click-drag", but instead of moving the screen over, my two grouped elements are shifted to the right. 

Perhaps my original comment about allowing a "fixed" element can be broadened to something along the lines of, "when Shift-click-dragging don't move elements, but instead navigate the screen."

Does this make more sense than my original comment?

BTW, thank you for the great tool!

**Comment by afdia** [comment]
Thanks for the explanation.
If you drag using the middle mouse button instead of the left one, you will always drag the diagram.
I guess this is what you wanted?

**Comment by laughlinbarker** [comment]
Marvelous! Yes. Need to learn the tool better apparently. Might be nice to do this on Shift-click-drag too for consistency sake (since that's the behavior when clicking non-element).

Thank you!

**Comment by afdia** [comment]
If there is no element under your mousecursor even left click without shift will move the whole diagram ;)
