### ISSUE TITLE
close umlet and cancel save popup -> umlet should not close

### ISSUE THREAD

**Issue by smumm** [umlet/umlet#250]
*how to reproduce*
- start umlet stand-alone
- add new class 
- close the application window by clicking the right top close symbol on window, or close the application window by pressing ALT-F4
- click 'cancel'
- the application closes

*expected*
- the application should not close

*specs*
- windows 7/8 64bit
- java version "1.8.0_20" (oracle)

**Comment by laughlinbarker** [comment]
Closes cleanly for me. Umlet 13.2, W7_32bit, Java 1.6

**Comment by smumm** [comment]
Found it on Windows 7 + 8.1 64bit using java 1.8. I will test it today on arch linux. this issue didn't occur with umlet 13.0 and the same specs.

**Comment by smumm** [comment]
Yes it is closing after you press cancel. But should not close, because you *canceled* the closing of the application.

**Comment by afdia** [comment]
I have changed the title to fit the description.

You're right, Umlet should probably not close in that case

**Comment by smumm** [comment]
yes 'X' and 'F4'. I would fix this but unfortunately it is very hard to get the project running with NetBeans.

**Comment by afdia** [comment]
fixed in #255
