### ISSUE TITLE
Sequence - All in one - add support for lost/found messages

### ISSUE THREAD

**Issue by peteruhnak** [umlet/umlet#251]
There's currently missing support for lost/found messages; they are very useful for events and splitting complex diagrams.

This is probably related to #198

Lost/found messages are described here http://www.omg.org/spec/UML/2.4/Superstructure/Beta2/PDF/
semantics in 14.3.18 Message
and the notation in 14.4 (table 14.2)

(dtto for UML 2.5 (http://www.omg.org/spec/UML/2.5/Beta2/PDF/))

**Comment by afdia** [comment]
resolved in new sequence AIO diagram
