### ISSUE TITLE
Custom Element Sticking Point

### ISSUE THREAD

**Issue by RadhiFadlillah** [umlet/umlet#258]
How to add sticking point in custom element ? 

I've followed the [tutorial](http://www.umlet.com/ce/ce.htm), but when I use `addStickingPoint()`, UMLet says that `method addStickingPoint() is undefined for the type CustomElementImpl`.

**Comment by afdia** [comment]
sorry this is currently not possible.

the code for this was removed some years ago (it caused several issues) and the tutorial is outdated unfortunately. I have forwarded the information to remove the last screenshot which mentions this possibility.

Currently we're rethinking the topic of Custom Elements to provide a lightweight variant which can be applied to every basic element.
If this approach works, you will be able to use an Element with a non-rectangular sticking polygon (like UseCase) as a basis and add some customizations to it.

Until then, unfortunately there is no way to change the rectangular sticking polygon.
