### ISSUE TITLE
Allow storage of UMLetino diagrams in common file hosting services (like Dropbox)

### ISSUE THREAD

**Issue by afdia** [umlet/umlet#266]
As suggested in #203 allow storage of diagrams in common file hosting services (like Dropbox)

Perhaps the following links are useful:
OAuth 2.0
https://en.wikipedia.org/wiki/OAuth
https://developers.google.com/accounts/cookbook/technologies/OAuth-2.0
https://blogs.dropbox.com/developers/2013/07/using-oauth-2-0-with-the-core-api/
https://www.dropbox.com/developers/reference/oauthguide

OpenID:
https://developers.google.com/accounts/cookbook/technologies/OpenID-Connect

**Comment by Montecito** [comment]
@afdia I implemented dropbox integration. I will soon create a pull request. best regards

**Comment by afdia** [comment]
solved in #271
