### ISSUE TITLE
Comments in relations rendered as caption/not ignored

### ISSUE THREAD

**Issue by sschober** [umlet/umlet#272]
In the FAQ it says:

> How to enter comments in a UML element description?
UMLet supports C++-style comments---starting a line with "//", eg, "//my comment..", will let UMLet ignore that markup line.

This lead me to the conclusion comments might also work in relation descriptions, but it seems that they don't. They are always displayed for me. Is there some other trick I'm missing?

I'm using Umlet 13.2 stand-alone.

**Some Background why I need this feature**

I'm writing a little tool that parses Perl code an generates and/or updates an Umlet diagram, while preserving arrangement of elements. To decide which relations are already present in the diagram and are "managed" by the tool, I decided to use an identifier (`class-name-source;class-name-target`), as computing source and target from clipping information seems to complicated and is not solving the second requirement. 

Naturally, I need that identifier to be preserved across Umlet edit sessions, so an extra XML tag is out of the question, as Umlet seems to remove unknown tags when it writes out diagrams. So, the option I'm going with is putting that identifier as a comment in the relation.

**Comment by afdia** [comment]
thanks for the report and cool idea :)

comments should work in every element, therefore this is an error which will be fixed in the next release after v13.3 (v13.3 is currently being finalized, therefore we probably won't add any additional changes)

**Comment by sschober** [comment]
Thank you very much!
