### ISSUE TITLE
UMLetino fails to load saved diagrams correctly

### ISSUE THREAD

**Issue by gerritgriebel** [umlet/umlet#286]
I wrote some weeks ago

    lt=.>
    Wöchentlich

for the following arrow and saved:

![bildschirmfoto 2015-06-30 um 16 19 28](https://cloud.githubusercontent.com/assets/3919675/8433113/246b5364-1f44-11e5-9fe4-9c49688a1195.png)

After loading it seems > was converted meanwhile magically to &amp;gt; entity.

PS: Welcome screen in UMLetino states still:
![bildschirmfoto 2015-06-30 um 16 19 55](https://cloud.githubusercontent.com/assets/3919675/8433210/b12a88c4-1f44-11e5-86b9-2f2d33bd5649.png)

**Comment by afdia** [comment]
Hi

Sorry this is a bug introduced in 13.3 during fixing #264 
It will be fixed in the next release (see issue #282)

Unfortunately escaping works slightly different for every storage location (file, browser storage and the soon available dropbox storage), but I hope I got it right in #282
