### ISSUE TITLE
Exporting diagrams ignores global fontsize property

### ISSUE THREAD

**Issue by tpoeppke** [umlet/umlet#290]
The fontsize property set globally with fontsize=x is ignored when exporting diagrams. On the other hand, specifying it for each element separately works as expected.

**Comment by afdia** [comment]
thanks for the report, will be fixed in the next release (maybe not v14 because we are already preparing the release, but v14.1)

In the meantime you can work around the issue by setting a global fontsize in the options. This one will get recognized by the export

**Comment by tpoeppke** [comment]
Thank you too for your efforts. UMLet is a really great tool!

**Comment by afdia** [comment]
thanks :)
