### ISSUE TITLE
Umletino: strg+space on empty line doesnt show all suggestions on firefox

### ISSUE THREAD

**Issue by afdia** [umlet/umlet#296]
the issue is probably caused by the new long autocompletion entries from the custom_elements= block
worked in v13.3

**Comment by hirzraimund** [comment]
The suggestions are displayed out of sight beneath the properties panel because the space above is to small. 
Should be fixed in https://github.com/umlet/umlet/pull/297

**Comment by afdia** [comment]
thanks for the fix, but there is one more problem: the codecompletion popup now has a fixed height which looks weird in case of fewer suggestions

An extreme case would be clicking right to a line which contains a valid command (e.g. "--")
it would be better if the height is a maxHeight and fewer entries only use fewer space (like before)
