### ISSUE TITLE
Textformatting not fully supported in GWT

### ISSUE THREAD

**Issue by hirzraimund** [umlet/umlet#300]
The textformatting commands Italics (/), bold (*) and underlined(_)  work in any combination in Umlet, but in GWT the underline format overwrites the other formats.
![image](https://cloud.githubusercontent.com/assets/5136683/9042036/3e6f49ae-3a0c-11e5-962c-5cce43926ab7.png)
left:Umlet  right:Umletino

The used properties text:
<pre>
_*/asd/*_
*_/asd/_*
*/_asd_/*

_/*asd*/_
/_*asd*_/
/*_asd_*/

*/asd/*
/*asd*/

_*asd*_
*_asd_*

_/asd/_
/_asd_/

/asd/
_asd_
*asd*
</pre>

**Comment by afdia** [comment]
thanks should be fixed now
