### ISSUE TITLE
Newlines don't work

### ISSUE THREAD

**Issue by przygienda** [umlet/umlet#308]
stuff like r1={set of \\active and\\passive peers}

used to split into newlines. Doesn't work anymore on 13.3 (albeit it still shows them when reading old diagrams)

**Comment by afdia** [comment]
Thanks for the report, the old relations interpreted \\ as a linebreak for r1 and r2 and this is currently missing for the new ones
This should be reimplemented in a future release

![rel](https://cloud.githubusercontent.com/assets/8770707/9568755/f858ecba-4f53-11e5-91e3-38d9ae353ee4.png)

Text:
lt=<<-
r1={r1 \\nextline\\nextline}
r2={r2 \\nextline\\nextline}
m1={m1 \\nextline\\nextline}
m2={m2 \\nextline\\nextline}

**Comment by afdia** [comment]
I've added linebreaks for new relations (for r1,r2 as well as m1,m2)
There is a small change in syntax though: you must use `\n` to make a linebreak (if this string should occur naturally, you can escape it with `\\n`

Here is an example how it works:
![new](https://cloud.githubusercontent.com/assets/8770707/13035382/0d1dcfe2-d34f-11e5-9da3-dcef83711c12.png)
Properties:
```
lt=-
r1=r1 a\nb\nc\n\nd\\neasdasdasd
m1=m1 a\nb\nc\n\nd\\neasdasdad
r2=r2 a\nb\nc\n\nd\\neasdasdasdas
m2=m2 a\nb\nc\n\nd\\neasasdasd
```

As you can see it also works for vertical relations, but the r and m texts can overlap and must be manually positioned to resolve the issue

**Comment by 71GA** [comment]
New lines don't work for example in a _"template class"_...
