### ISSUE TITLE
Class in Class Diagramm grey when inside package

### ISSUE THREAD

**Issue by Dr3la** [umlet/umlet#311]
Classes in a class diagram that are created after a package has been added have a different text color when inside this package. Classes that were created before the package always have normal text color
![umlet](https://cloud.githubusercontent.com/assets/2946403/9954322/6063b928-5de8-11e5-8460-bfcc749e8699.PNG)

Steps to reproduce:
1. New Diagram
2. Add class
3. Add Package
4. Put Class into package

The source of the problems seems to be that the semi-transparent package is rendered "over" the class. However, there is no mechanism for z-ordering the elements.

**Comment by afdia** [comment]
Hi

You can give the background element a lower layer (which is equal to the z-order)

If you put "layer=-1" into the text of the package, it will be placed behind every non-layered element (as layer=0 is the default)

**Comment by Dr3la** [comment]
sfdia, thanks for the workaround!
I still think this is an issue though since there is neither UI support for it nor is it explained in the example.

**Comment by afdia** [comment]
It's true that the text based approach of UMLet can be unintuitive at first for new users, but we try to put every possible command somewhere in a fitting palette.
In addition you can press "ctrl+space" in a new line and see all possible commands

In terms of layering, there is the "Generic Layers" Palette which shows how layers work and there is the context menu entry "Layer -> to front/back" as a simple UI support.

**Comment by Dr3la** [comment]
I see, thanks for your quick responses! I'll close this issue ;)
