### ISSUE TITLE
"relations" behaviour in UXF file

### ISSUE THREAD

**Issue by ramyadirsumilli** [umlet/umlet#313]
I am using the UML diagram for further transformation using Java. I would like to understand about "relations" behavior in UXF file. In concern to the relation in UXF file, how does coordinates and additional attributes contribute?
In simple, I want to find out which two elements are connected by the relation using its coordinates. How can I find this?

**Comment by afdia** [comment]
Hi

As you can see in the uxf file, the additional attributes of a relation are the points of a relation
An element is connected to a relation if the stickingpolygon of the element is near an endpoint of a relation (I thing <10px on 100% zoom, <9 on 90% and so on)

So there is no clear indication which relation sticks to which element, it's just calculated on the fly based on the position
You can check out the StickablesTest.java class which shows some tests about the sticking behavior
