### ISSUE TITLE
Package umllet as standalone Mac App

### ISSUE THREAD

**Issue by jayshao** [umlet/umlet#316]
It would be nice to have an app bundle for the mac, esp. on that was installable via homebrew cask

**Comment by alisterdev** [comment]
+1

**Comment by joseangeljimenez** [comment]
+1

**Comment by FrazJ** [comment]
+1

**Comment by barthel** [comment]
UMLet is available via homebrew: https://github.com/Homebrew/homebrew-core/pull/900.

**Comment by jekuno** [comment]
Yes, the most recent version of Umlet (which is v14.2 as of now) can be installed via `brew install umlet`.
Issue can be closed.

**Comment by barthel** [comment]
With UMLet 14.3 there is a (also macOS) tweaked umlet.sh see: https://github.com/umlet/umlet/issues/495
Trying to create a real macOS application fails with various reasons see: https://github.com/umlet/umlet/issues/499

@afdia Please close this issue.
