### ISSUE TITLE
License file is missing

### ISSUE THREAD

**Issue by werediver** [umlet/umlet#318]
The [home page](http://www.umlet.com/) of the project states:

> Distributed under the GNU General Public License.

But the repository contains no license file, so one can't easily tell what is allowed and what is not.

This is what GitHub says about missing license file:

> Generally speaking, the absence of a license means that the default copyright laws apply. This means that you retain all rights to your source code and that nobody else may reproduce, distribute, or create derivative works from your work. **This might not be what you intend.**

https://help.github.com/articles/open-source-licensing/#what-happens-if-i-dont-choose-a-license

At the end of that page there is also a hint on how to add a license file quickly:

>  when you are on a repository home page, you can click on the + icon. To make the process easier, if you name the newly created file LICENSE.md, the license picker automatically appears.

*P.S. I find UMLet to be a very interesting project. Thanks for your effort!*

**Comment by werediver** [comment]
Ok, it was a little bit too hastily. There is a license file at [Baselet/LICENCE.txt](https://github.com/umlet/umlet/blob/master/Baselet/LICENCE.txt), but that's not clear if it also relates to BaseletElements and BaseletGWT directories which has no such files.

Is there any concerns with placing that file at the repository root?

**Comment by afdia** [comment]
I moved the file to the root
It was in Baselet because few years ago this was the only subproject, but you're right that it should be at the root dir because it applies to the whole source code
thanks
