### ISSUE TITLE
Feature Request: Any chance of an XMI save or export format?

### ISSUE THREAD

**Issue by JamieOBE** [umlet/umlet#321]
Nice tool - don't think I can work with UXF though as I want to do a bit more than just diagramming... Any plans for XMI? 
Thanks!
Jamie

**Comment by afdia** [comment]
Sorry I've overlooked this request.
We only have limited resources and implementing an XMI format would be time consuming and we would still have to be backwards compatible to UXF, therefore we do not plan to implement it at the moment.

But it should be quite simple to extract information from UXF files. The GWT UXF parser can be found at https://github.com/umlet/umlet/blob/master/umlet-gwt/src/main/java/com/baselet/gwt/client/element/DiagramXmlParser.java and is very basic and simple but only handles the new grid elements.
If you want to parse the deprecated old grid elements (with the red background when selected) you should look at the parser for umlet standalone/plugin: https://github.com/umlet/umlet/blob/master/umlet-swing/src/main/java/com/baselet/diagram/io/DiagramFileHandler.java

**Comment by afdia** [comment]
Hi
Umlet calculates border-connected-relations during a move of an element on the fly, so no there is no explicit list of connections.

The logic in Umlet which handles this is mostly in classes like:
https://github.com/umlet/umlet/blob/master/umlet-elements/src/main/java/com/baselet/element/sticking/Stickables.java
https://github.com/umlet/umlet/blob/master/umlet-elements/src/main/java/com/baselet/element/sticking/StickingPolygon.java
