### ISSUE TITLE
Umlet plugin does not work in eclipse cdt

### ISSUE THREAD

**Issue by pischky** [umlet/umlet#331]
I have tried 
Eclipse IDE for C/C++ Developers

Version: Mars Release (4.5.0)
Build id: 20150621-1200
And the File>New>Other>Other does not show the UMLet option. In Java or JEE it is working.
Any other requirements missing?

**Comment by afdia** [comment]
Hi
Thanks for reporting

This is a known issue #306 which will be fixed with the next release.
As the user in the other issue reported, v12.2 should work in the meantime

**Comment by pischky** [comment]
Thank you very much for your fast response and help. Modified the jar, used "eclipse.exe -clean" and it works!
