### ISSUE TITLE
Font size isn't respected in exported files

### ISSUE THREAD

**Issue by gronostajo** [umlet/umlet#342]
Exported files always use default font size. I've tested SVG and PNG. With default font size exported images look like expected, but when I have non-standard font size selected, text is getting cut off.

Default font size, UMLet 13.3 screenshot vs. exported PNG:

![UMLet screenshot, default font](https://cloud.githubusercontent.com/assets/1347866/12074141/cfb1fb1a-b143-11e5-9334-f4351f58b8a3.png)
![Exported PNG, default font](https://cloud.githubusercontent.com/assets/1347866/12074142/dd727e1e-b143-11e5-9db5-bcc1f84463e5.png)

Font size = 12, UMLet 13.3 screenshot vs. exported PNG:

![UMLet screenshot, fontsize=12](https://cloud.githubusercontent.com/assets/1347866/12074144/f2c2b572-b143-11e5-95ef-2bd890fdcf69.png)
![Exported PNG, fontsize=12](https://cloud.githubusercontent.com/assets/1347866/12074145/fd9c4ca6-b143-11e5-8d76-56fb58ade8aa.png)

I'm using JRE 8u66 and UMLet 13.3. UMLet 13.2 isn't affected:

![PNG exported from UMLet 13.2](https://cloud.githubusercontent.com/assets/1347866/12074154/87bee6e6-b144-11e5-8a3e-be04344a9d5b.png)

**Comment by afdia** [comment]
thanks for the report, this has been fixed in #290

We will release the next version with the fix soon
