### ISSUE TITLE
Create stickable custom line element

### ISSUE THREAD

**Issue by dicastro** [umlet/umlet#350]
Is it possible to create a new stickable custom line element?

Il would like to create custom linetypes for ER diagram.

**Comment by afdia** [comment]
Relations cannot be customized in the same way Custom Elements can, but they offer a variety of combinations out of the box, perhaps you will find a fitting line ending/type/...

The best way to search for them is to check the palettes or you press Ctrl+Space while the cursor is in an empty line in the properties text of the relation (it will list all possible customizations)

Of course you could also check out the code, change the relation class and build a local version of UMLet, but that's typically more work than simply writing a custom element
