### ISSUE TITLE
Please highlight the circles of relation corners and endpoints on mouseover

### ISSUE THREAD

**Issue by lanoxx** [umlet/umlet#354]
Hi Umlet devs,

I would like to request a small enhancement for your great UMLet tool. Currently when I select a relation arrow, then its endpoints and all corner points are rendered with a little circle that can be grabbed in order to drag the points around on the screen.

It would be great if there was some visual feedback when I enter the circle array with the mouse, in order to indicate that the circle is now active and the point will move when I drag the mouse around.

You could for example draw the circle bold or change its color. 

The same thing would be nice for the little square that is drawn at the center of the relation arrow and which allows dragging the whole arrow around the screen. I often find my self dragging a single point on the arrow line instead of grabbing the whole relation arrow.

Cheers and thanks for this nice program.

**Comment by lanoxx** [comment]
P.S. I am using the latest stand alone version of UMLet.

**Comment by afdia** [comment]
Hi
Additional visual feedback for the action which will happen on relations sounds reasonable.

Changing the color of the circle/dragbox sounds good, but perhaps it would be better to change the cursor to another one. This is already used for the distinction between dragging and resizing of elements and has the advantage that it would also work for relations which are not selected (the color highlighting would probably be distracting if it would be enabled for non selected relations)

**Comment by lanoxx** [comment]
Hi Andreas,

Sounds good. Maybe a combination of both would be a good idea where the cursor always changes and the circle only for selected relations?

**Comment by afdia** [comment]
I have checked the old relations and they had different cursors, therefore I reused them for the new relations.

Special coloring on hover is currently not implemented, because it would not be that easy to implement.

(commit e341cc6fc24457aa0f0fd0d1c225c733ae9158cf)

**Comment by lanoxx** [comment]
Good job. Many thanks for fixing this so fast. Colors or some hover effect would still be nice but I can also live with the current solution. Also many thanks for spotting and fixing issue #358, that always annoyed me a little but I thought I was just grabbing at the wrong location.
