### ISSUE TITLE
Sequence all-in-one: Borders broken during exported

### ISSUE THREAD

**Issue by FichteFoll** [umlet/umlet#356]
```
title=Test
obj=A~a
obj=B~b 

a->b
```

![test2](https://cloud.githubusercontent.com/assets/931051/13030327/fd15b022-d2a6-11e5-8003-dc15a6b2e95d.png)

This is the case for at least png, svg, jpg and pdf. Sometimes the bottom line is visible, sometimes not.

Also note the title lines exceeding the base rect.

**Comment by afdia** [comment]
Thanks for the report. The bug is the same as #353 and will be fixed in v14.2

**Comment by FichteFoll** [comment]
Nice. Do you have an ETA?

**Comment by afdia** [comment]
Currently not sorry, but you can checkout the master branch and build it locally if you need it asap.
Infos about how to do that can be found at https://github.com/umlet/umlet/wiki/Information-for-Developers
