### ISSUE TITLE
when having text element with style=wordwrap the wordwrap does not work correct

### ISSUE THREAD

**Issue by simple2** [umlet/umlet#363]
when having a text element like
```
MessagePresenter (text)
style=wordwrap
```
and the box cuts off at the middle of the word, this word will be shown twice like:
```
MessagePrese
MessagePresenter
(text)
```

Tested with Standalone Version 14.1.1

**Comment by afdia** [comment]
Thanks for the report this is indeed an error. It should be quite simple to fix.

**Comment by afdia** [comment]
was not that simple but now it works. I've also added some testcases to make sure it won't break in the future
