### ISSUE TITLE
element type is not shown (changeable) in gui

### ISSUE THREAD

**Issue by simple2** [umlet/umlet#364]
It would be nice to show the element type in the gui.
It would be even better if it would be possible to change the type by clicking on it and selecting a different type. This would be very helpful to change deprecated types to new types.

Tested with Standalone Version 14.1.1

**Comment by afdia** [comment]
If you enable the developer mode in the options, you will see the type on new elements
But you are right that the classname of old elements is still not shown and should probably be shown too to help with the migration

**Comment by afdia** [comment]
the next version will also show the type of the deprecated grid elements (to make the migration easier)
