### ISSUE TITLE
is the xml file format documented?

### ISSUE THREAD

**Issue by 75lb** [umlet/umlet#365]
is the `.uxf` xml file format documented anywhere? I'd like to parse javascript source and generate uxf files..

**Comment by afdia** [comment]
There is no official xsd for the uxf format, but it's quite simple. If you create a diagram with a UML class, a UML relation and perhaps a deprecated UML class as well as a deprecated UML relation (if you need to support those too), you should see every possible XML element if an UXF file.

Or you can checkout the XML parsing code of UMLet which is old but should not be too hard to understand:
https://github.com/umlet/umlet/blob/master/umlet-swing/src/main/java/com/baselet/diagram/io/DiagramFileHandler.java
https://github.com/umlet/umlet/blob/master/umlet-swing/src/main/java/com/baselet/diagram/io/InputHandler.java
https://github.com/umlet/umlet/blob/master/umlet-gwt/src/main/java/com/baselet/gwt/client/element/DiagramXmlParser.java

The first 2 classes are the xml parsers for standalone UMLet, the last one is the GWT XML parser for Umletino (which is limited to new grid elements)

**Comment by 75lb** [comment]
ok, thanks for the info - i will look into it :+1:
