### ISSUE TITLE
When exporting <<execution environent>> the bottom line is not included

### ISSUE THREAD

**Issue by j3h4** [umlet/umlet#372]
See attached PNG and UXF. The same issue is in all export formats.

![test](https://cloud.githubusercontent.com/assets/1474502/14347477/886ee1fe-fcb7-11e5-809e-6fd8d6bc6984.png)

**Comment by afdia** [comment]
Thanks for the report, this is the same issue as in #353 which will be fixed with the next release (hopefully in the next few days)
