### ISSUE TITLE
UMLet 14.2 not working with Eclipse Mars.2 (4.5.2) 64 bit JDT

### ISSUE THREAD

**Issue by Clocktown** [umlet/umlet#375]
**While I have no idea what caused this behaviour, it is now fixed since I upgraded to Ubuntu 16.04 LTS. One or another package must have caused the problem. The only thing I had to do on 16.04 was add `export SWT_GTK3=0` to my .profile, because Eclipse got goddamn slow and I couldn't even create a Project, it would take forever, but this doesn't concern UMLet anyways. Now everything works, so should anyone encounter the same problem: upgrade to 16.04 LTS!**
When I try to open a diagram or create a new one, Eclipse either crashes, or Java freezes (killing Eclipse does not help, I need to kill Java with -SIGKILL after opening console with STRG+ALT+F1).
At first I tried with the Eclipse version that you simply unpack. Java froze, when I deleted workspace and started with -clean instead of freezing it just crashed.
So I trashed that and now I tried it with Eclipse installed via Eclipse Installer, and it just crashed. Now without even without an error popping up.
I'm talking about the JDT, not the CDT. I'm on Ubuntu 15.10 64 bit.

Edit:
I started it again via console, this time I actually got some kind of info why it crashes, this wasn't there before:
```
[xcb] Unknown sequence number while processing queue
[xcb] Most likely this is a multi-threaded client and XInitThreads has not been called
[xcb] Aborting, sorry about that.
java: ../../src/xcb_io.c:274: poll_for_event: Assertion »!xcb_xlib_threads_sequence_lost« not fulfilled.
```
Edit2:
Tried it again with new workspace and -clean, this time it froze and I had to kill Java as described above, so no logfile.
When I started Eclipse again, the diagram file was there, when I tried to open it Eclipse crashed again but this time, thankfully, with an error window:
```
JVM terminated. Exit code=1
/usr/lib/jvm/java-7-openjdk-amd64/jre/bin/java
-Dosgi.requiredJavaVersion=1.7
-XX:MaxPermSize=256m
-Xms256m
-Xmx1024m
-Declipse.p2.max.threads=10
-Doomph.update.url=http://download.eclipse.org/oomph/updates/milestone/latest
-Doomph.redirection.index.redirection=index:/->http://git.eclipse.org/c/oomph/org.eclipse.oomph.git/plain/setups/
-jar /home/clocktown/eclipse-jdt/eclipse//../../.p2/pool/plugins/org.eclipse.equinox.launcher_1.3.100.v20150511-1540.jar
-os linux
-ws gtk
-arch x86_64
-showsplash
-launcher /home/clocktown/eclipse-jdt/eclipse/eclipse
-name Eclipse
--launcher.library /home/clocktown/eclipse-jdt/eclipse//../../.p2/pool/plugins/org.eclipse.equinox.launcher.gtk.linux.x86_64_1.1.300.v20150602-1417/eclipse_1612.so
-startup /home/clocktown/eclipse-jdt/eclipse//../../.p2/pool/plugins/org.eclipse.equinox.launcher_1.3.100.v20150511-1540.jar
--launcher.appendVmargs
-exitdata 25000a
-product org.eclipse.epp.package.java.product
-install /home/clocktown/eclipse-jdt/eclipse
-vm /usr/lib/jvm/java-7-openjdk-amd64/jre/bin/java
-vmargs
-Dosgi.requiredJavaVersion=1.7
-XX:MaxPermSize=256m
-Xms256m
-Xmx1024m
-Declipse.p2.max.threads=10
-Doomph.update.url=http://download.eclipse.org/oomph/updates/milestone/latest
-Doomph.redirection.index.redirection=index:/->http://git.eclipse.org/c/oomph/org.eclipse.oomph.git/plain/setups/
-jar /home/clocktown/eclipse-jdt/eclipse//../../.p2/pool/plugins/org.eclipse.equinox.launcher_1.3.100.v20150511-1540.jar 
```
And a .log:
```
!SESSION 2016-04-21 20:21:59.733 -----------------------------------------------
eclipse.buildId=4.5.2.M20160212-1500
java.version=1.7.0_95
java.vendor=Oracle Corporation
BootLoader constants: OS=linux, ARCH=x86_64, WS=gtk, NL=de_DE
Framework arguments:  -product org.eclipse.epp.package.java.product
Command-line arguments:  -os linux -ws gtk -arch x86_64 -product org.eclipse.epp.package.java.product

!ENTRY org.eclipse.core.resources 2 10035 2016-04-21 20:22:03.894
!MESSAGE The workspace exited with unsaved changes in the previous session; refreshing workspace to recover changes.

```
Edit3:
14.1, 13.3 and 12.2 also aren't working.
And even 14.2 as a standalone, while it does run, it just freezes completely after a short while and, like with the Eclipse plugin, I have to open console with STRG+ALT+F1 to kill it.

**Comment by afdia** [comment]
thanks for the detailed report, it will probably help other users as well
