### ISSUE TITLE
Download on UMLet website contains trojan

### ISSUE THREAD

**Issue by natevaughan** [umlet/umlet#383]
![capture](https://cloud.githubusercontent.com/assets/12039822/15192224/e3957ab2-177d-11e6-86ee-11ae427d5671.PNG)

**Comment by afdia** [comment]
Hi
It does not contain a trojan, this is a false positive from the Win10 virus scanner (see #377 where several other virus scanners are run on the zip file)

Unfortunately it seems to be impossible to run the Win10 virus scanner without having a local Win10 installation which makes detecting and fixing the error complicated.

I close this as a duplicate to make sure we focus information on one issue.

**Comment by natevaughan** [comment]
Sorry that I missed the duplicate ticket. For what it's worth, I'm running Windows 7

**Comment by natevaughan** [comment]
It was Windows Defender.

**Comment by afdia** [comment]
Thats weird, I have tried Windows Defender and MS Security Essentials, and both don't "detect a trojan" on my Windows7 PC.
Can you try to update the Virus definitions and check it again. Does it still detect it as a trojan or is it working with the current definitions?

Perhaps we are doing something different; I have opened Windows Defender and used the "Scan custom directory" functionality on a directory which contains the file I downloaded from http://umlet.com/umlet_14_2/umlet-standalone-14.2.zip
Do you do the same?
