### ISSUE TITLE
Download of 14.2 reported as unsafe by InternetExplorer

### ISSUE THREAD

**Issue by robertlugg** [umlet/umlet#386]
I attempted to download 14.2 and it was flagged by "SmartScreen" filter in IE (from the umlet website).  Please consider the following link:
https://feedback.smartscreen.microsoft.com/smartscreenfaq.aspx

14.1 seems to be OK.

My request to anyone reading this is to download it in IE.  Then right-click on it to report it as safe.  Also, the author should do the same.

I haven't actually scanned it for problems nor have any idea why it was flagged.

I now see that this is a duplicate of issue #377.  This is indeed still an issue.  As mentioned above, I suggest going to the Microsoft website and voting that it's OK.

**Comment by afdia** [comment]
thanks for the report, I have reopened the other issue to make it visible to other users.

**Comment by afdia** [comment]
should be fixed by now (by MS)
