### ISSUE TITLE
Export to PDF with Hebrew Words ,get a missing words

### ISSUE THREAD

**Issue by VirtualL** [umlet/umlet#387]
When performing EXPORT to PDF file and in the project tere is  Words in **Hebrew**.
UMLET export it without  all the words recorded in Hebrew. i am using umletV14.2
[
![image](https://cloud.githubusercontent.com/assets/10164935/15742338/f1356740-28c6-11e6-8bc0-7247de552b38.png)
](url)

**Comment by afdia** [comment]
Hi

This is because the pdf uses a system font which doesn't support UTF8
You must select and embedd a UTF8 font into the pdf to make it work
see #162
