### ISSUE TITLE
Transparency not working for UML Sequence

### ISSUE THREAD

**Issue by JoeyCorleone** [umlet/umlet#388]
Hi,
please correct me if I'm doing it wrong, but it seems like there are elements in UML Sequence which are not affected by the transparency setting.

E.g. if I have a box with transparency=0 and lifeline without transparency setting (or with transparency 100), I am able to see the lifeline even if the box is placed above it.

The same is true for the ":Instance" element. I haven't tested further elements.

System: UMLet 14.2, OpenJDK 1.8.0_91, Linux

**Comment by afdia** [comment]
Hi

Transparency alone doesn't decide whether overlapping elements are visible. Try using the "layer" command to overwrite the default z-order.

So if you want an ":instance" element to be in front of a relation, put it on layer=10 (iirc the default layer of most elements is 0, except for relations which are on layer 1)

**Comment by JoeyCorleone** [comment]
I wasn't aware of this.
It works fine using different layers.

Thank you!
