### ISSUE TITLE
Arrowed lines with large lw become rectangles 

### ISSUE THREAD

**Issue by robertlugg** [umlet/umlet#400]
Create an arrow as follows:
lt=<<<->>>
lw=25
The result is:
![image 214](https://cloud.githubusercontent.com/assets/6054540/18330808/903c2ace-750f-11e6-94ed-d9269811342d.png)

I believe the problem is that the linewidth is also applied to the ends of the lines.  Please adjust, if possible, so any linewidth will render correctly.

**Comment by afdia** [comment]
The positioning of the arrow ends is fixed and therefore unfortunately starts to look ugly after certain values.
To fix it, the lw value must be read and the arrow ends must be displaced accordingly.
The example also shows that the relation size is too small to display the whole arrow (therefore they are cut off at the tips). To fix it, large lw values must also increase the size of the relation (or Umlet must switch to one large canvas to draw on like Umletino).

**Comment by robertlugg** [comment]
It seems like its not worth fixing/enhancing.  I'm certainly OK with that so I am closing the issue.  Thanks for taking it into consideration.
