### ISSUE TITLE
Decision Nodes should print text

### ISSUE THREAD

**Issue by afdia** [umlet/umlet#402]
If someone tries to model an ER diagram he might need to put description text into the decision diamond.

This was possible with the old element from the ER palette:
![new](https://cloud.githubusercontent.com/assets/8770707/18616542/0c62ee60-7dbe-11e6-95d4-bd8ad503762a.png)
uxf: https://gist.github.com/afdia/31f8efd04d5fde7f2b0b7058b37077e6

It should be possible with the new element as well (simply print the text centered)

**Comment by nitinsurana** [comment]
+1

**Comment by JBerny** [comment]
ER is not supported anymore, maybe you could close this one?

**Comment by afdia** [comment]
While it's true that there is no explicit palette for ER diagrams anymore, you can still use elements from any other palette to build a basic ER diagram.

I have fixed the issue and the decision diamond can not be filled with text which will be centered.
