### ISSUE TITLE
Foreground (fg) and background (bg) message text color in "Sequence - All in one" elements?

### ISSUE THREAD

**Issue by genpfault** [umlet/umlet#403]
How can I set the foreground/background color on message text on "Sequence - All in one" elements?

Something like this:

```
title=Title
obj=A~A
obj=B~B
fg=red
A->>>B : Text
```

Things like `fg=red; A->>>B : Text` or `A->>>B : Text; fg=red` seem like they ought to work but just result in parse errors.

**Comment by afdia** [comment]
At the moment you can only set the fg and bg for the whole element but not for parts of it
