### ISSUE TITLE
Autoresize Determines Line Length Incorrectly When Line Starts With Spaces

### ISSUE THREAD

**Issue by jimtahu** [umlet/umlet#406]
UMLet version 14.2 2016-04-03

Classes with "style=autoresize" determines line length incorrectly when line starts with spaces, and the end gets cut off. 

See the attached xml/png:
![poorresizingexample](https://cloud.githubusercontent.com/assets/1667208/19872157/505a4322-9f86-11e6-9962-3e5545be7438.png)
[PoorResizingExample.zip](https://github.com/umlet/umlet/files/562908/PoorResizingExample.zip)

I think the length is being determined with the spaces trimmed off.

**Comment by afdia** [comment]
Thanks for the report, it will be fixed in the next release.
