### ISSUE TITLE
Element must have a single child element: <g:east size='200'> 

### ISSUE THREAD

**Issue by Neo110** [umlet/umlet#413]
Element must have a single child element: <g:east size='200'>    how to change this  ? I not need g:east

**Comment by afdia** [comment]
Please stop spamming the issue tracker with such questions, it is only meant for issues with using UMLet.
We do not have the time to give personal support on how to build the projects.

There is some information in our wiki: https://github.com/umlet/umlet/wiki/Information-for-Developers
Other than that, you will have to learn Java Swing for standalone UMLet, Eclipse PDE for the eclipse plugin and Google web toolkit (GWT) for the web version.
