### ISSUE TITLE
[critical] Simple freeze

### ISSUE THREAD

**Issue by Kcorab** [umlet/umlet#418]
I have found a critical bug that freezes UMLet.

To reproduce do the following:

Choose this diagram element. (composite structure)
`lt=[].>`

Now select this diagram element and move the middle circle (kink of the edge) to the beginning (the port) or end (arrow) of this diagram element. The application is going to freeze.

![bug_reproduce](https://cloud.githubusercontent.com/assets/7406477/20867725/2f60134c-ba4b-11e6-81fc-8d06abb787c0.png)

Used system:
UMLet version 14.2 2016-04-03 on Arch Linux

**Comment by afdia** [comment]
Thanks for the report.
I cannot reproduce the problem in Windows7, but Linux Mint hangs with UMLet 14.2 and openjdk 1.8.0.72.

It's really a weird issue, because we don't do something differently depending on the OS.

**Comment by MartinX3** [comment]
I reproduce the freeze quite often
happens, wenn the arrow wants to turn 180°. GRARGHHH

**Comment by Kcorab** [comment]
This issue is an duplicate. Please refer to https://github.com/umlet/umlet/issues/349.
