### ISSUE TITLE
multiline qualifiers

### ISSUE THREAD

**Issue by daniel63dm** [umlet/umlet#432]
**I'd like to write multi-line  qualifiers like bellow.**

![image](https://cloud.githubusercontent.com/assets/15101495/23119686/7f35bf02-f759-11e6-8099-f26db3ce9863.png)

`lt=[myQualifier]-
m2=1    1`

**Comment by afdia** [comment]
This is possible, just write `\n`

E.g.:
```
lt=<->
m2=line1\nline2\nline3
r2=line1\nline2\nline3
```
![grafik](https://cloud.githubusercontent.com/assets/8770707/23510077/6eded40c-ff58-11e6-9191-45bc387a7a0b.png)
