### ISSUE TITLE
Missing menu mnemonics.

### ISSUE THREAD

**Issue by garretwilson** [umlet/umlet#445]
There are so many UI details that have been overlooked. The application (which I only use to export files because the plugin hangs, reported in #310 and others) doesn't have any menu mnemonics for `File | Recent files`. (Normally this would be `r`, that is, so I can hit `Alt+F, r`.

Similarly there is no mnemonic for `File | Export as...`. (Don't use `x`, because that is used for "Exit".)

Actually I just realized that none of them have mnemonics. ☹️

I would suggest looking at other applications and trying to use a convention. (People have even collected lists of these conventions. I can point you to them if you can't find them.)

(Note that in this description I originally used the word "shortcut" instead of "mnemonic", which partly explains the confusion below. I have since updated the description to be clearer.)

**Comment by afdia** [comment]
> Actually I just realized that none of them have shortcuts. ☹️

What do you mean with none have shortcuts? Most menu items have shortcuts which are visible if you open the menu in Standalone UMLet (new is Ctrl+N, open is Ctrl+O, ...)

I agree that we should think about adding the missing ones, but recent files and export have submenus, so you would only open this submenu which may not be useful.

Ctrl+R for recent files sounds fine, but perhaps we should make it similar to Gimp which uses Ctrl+1 for the top recent file, Ctrl+2 for the next one and so on. I don't know if this is a usual behavior, but it sounds more useful because the shortcuts target the submenus directly instead of opening the submenu.

Gimp also uses Ctrl+E for export, but UMLet has another nested menu with the export format here so it is a bit more complicated than in Gimp. Perhaps Ctrl+E should open the first export entry; the user can still change the filetype in the filechooser popup.

Ctrl+X is already used for "Cut" so it cannot be assigned to export

**Comment by garretwilson** [comment]
Wait, @afdia !!! You misunderstood the issue! (Perhaps I didn't explain it well.) Please don't implement `Ctrl+R`, etc.!

I will admit that the word "shortcut" is very general and could be ambiguous. I was referring to the underlined letters on each menu item that allow you to go quickly to that menu item after opening the menu. I didn't mean global accelerator key combinations. You're right, "shortcut" can be used for both.

What I'm referred to is probably best described as "mnemonics"; see the explanation and photo on [Wikipedia](https://en.wikipedia.org/wiki/Mnemonics_(keyboard)).

I'll update this issue description.

**Comment by garretwilson** [comment]
Here, read this [recommendation by Eclipse itself](http://help.eclipse.org/neon/index.jsp?topic=%2Forg.eclipse.platform.doc.isv%2Freference%2Fmisc%2Fui_accessibility_tips.html):

> **Assign mnemonics to all menus and menu items.** Ensure they are unique within a given menu. …

And this appears to be the the Eclipse plugin guide; read about mnemonics here:

http://help.eclipse.org/neon/index.jsp?topic=%2Forg.eclipse.platform.doc.isv%2Fguide%2Fworkbench_cmd_menus.htm

http://help.eclipse.org/neon/index.jsp?topic=%2Forg.eclipse.platform.doc.isv%2Freference%2Fextension-points%2Forg_eclipse_ui_menus.html

**Comment by afdia** [comment]
Mnemonics are currently added alongside the global ctrl-based shortcuts (so if a menu entry has the shortcut ctrl+N, the mnemonic is automatically assigned to N).

This simple way of assigning them has some problems: if the shortcut is not part of the word, it will not be underlined (e.g. Ctrl+W for closing assigns W as mnemonic which works but is invisible)
Also menu items without global shortcuts (such as related files) are missing mnemonics too.

Perhaps the logic should be changed to be more flexible by decoupling mnemonics from global shortcuts (e.g. Eclipse also assigns Ctrl+W to the close action, but uses the mnemonic C. It uses W as the mnemonic for switching workspaces)
Then we could assign R for recent files, but still have no direct global shortcut for it and we could change the close mnemonic to C which makes it visible by underlining the C in close)

**Comment by garretwilson** [comment]
> Mnemonics are currently added alongside the global ctrl-based shortcuts (so if a menu entry has the shortcut ctrl+N, the mnemonic is automatically assigned to N).

Is that something you're doing, or Eclipse is doing, or Swing is doing? You mentioned once you are using Swing. I have used Swing extensively, and the global shortcuts are in no way related to the pull-down menu mnemonics, so if you're using swing you must be making this association yourself.

> Perhaps the logic should be changed to be more flexible by decoupling mnemonics from global shortcuts ...

Yes indeed. As I mentioned, I expect to type `Alt+F > R` to access the recent files from the files menu. But I do *not* expect that functionality by a global `Ctrl + R` shortcut. (That wouldn't make sense, anyway: the recent files list is a submenu of the `Files` menu.)
