### ISSUE TITLE
style=wordwrap doesn't take leading spaces into account.

### ISSUE THREAD

**Issue by VincentBeltman** [umlet/umlet#460]
When you create a simple rectangle (Like SimpleClass for example) and add style=wordwrap, it works fine. But if you add leading spaces (like in the picture), it doesn't wrap the text right. "text" should be on the next line.
![wordwrap bug](https://user-images.githubusercontent.com/4235174/26878275-42b587dc-4b8d-11e7-8b9a-ad71ddc25fae.PNG)

**Comment by HagarGadallah** [comment]
I guess it is working properly for me now?
![screenshot 185](https://user-images.githubusercontent.com/17953870/33952954-10d9487c-e03c-11e7-9a62-ec4de2449002.png)

**Comment by afdia** [comment]
I can reproduce the issue using the following text:
```
style=wordwrap

            some text that should
```
![grafik](https://user-images.githubusercontent.com/8770707/33953418-2e08250a-e035-11e7-81a1-bbef537bccec.png)

I guess the wordwrap code is truncating the text before checking the width
