### ISSUE TITLE
Installation via Eclipse Marketplace

### ISSUE THREAD

**Issue by d53dave** [umlet/umlet#465]
Hello,

when searching for UMLet on a very popular search engine, the eclipse marketplace website is a very prominent result, with a very recent date, which makes it even more relevant.

However, when searching the Marketplace from within Eclipse Oxygen, I am unable to find, and therefore, install UMLet.

It would be great to have a proper integration with the marketplace.

**Comment by afdia** [comment]
We are currently working on getting umlet into the marketplace
The implementation of a p2 repository (update site) is done (see #289) but unfortunately you cannot install plugins from the marketplace but only features, therefore we are trying to get the feature up and running.

**Comment by barthel** [comment]
How is the status of this item?
It's a pain to install the UMLet Eclipse plugin on macOS because it is not signed.

**Comment by paulvi** [comment]
PLease update https://marketplace.eclipse.org/content/umlet-uml-tool-fast-uml-diagrams with feature id,

to enable install via drag-n-drop and Marketplace client

**Comment by afdia** [comment]
umlet is now available via marketplace
update site is http://www.umlet.com/umlet_latest/repository
