### ISSUE TITLE
extending umlet:  \gen folder does not exist

### ISSUE THREAD

**Issue by rafads7** [umlet/umlet#473]
Hi, I am a bit new on this and I am trying to extend umlet code, then I downloaded all the code and opened in IntelliJ IDEA but when I am trying to build the project I get many errors saying many classes do not exist. For example:

`C:\Users\rafad\IdeaProjects\umlet\umlet-elements\src\main\java\com\baselet\element\facet\customdrawings\CustomDrawingParserImpl.java
Error:(4, 52) java: package com.baselet.element.facet.customdrawings.gen does not exist
Error:(5, 52) java: package com.baselet.element.facet.customdrawings.gen does not exist
Error:(6, 52) java: package com.baselet.element.facet.customdrawings.gen does not exist
Error:(7, 52) java: package com.baselet.element.facet.customdrawings.gen does not exist
Error:(8, 52) java: package com.baselet.element.facet.customdrawings.gen does not exist
Error:(9, 52) java: package com.baselet.element.facet.customdrawings.gen does not exist`

what should I do to generate those folders and the classes that are left? 
Thank you!

**Comment by afdia** [comment]
You must run `mvn clean install` at least once to make sure all classes are generated, Afterwards you can build using your IDE as long as you don't change the generated classes.

You can also check the mvn build log from travis: https://travis-ci.org/umlet/umlet
