### ISSUE TITLE
Request Explicit XML Tag to Specify Associations Between Arrow and Box

### ISSUE THREAD

**Issue by JitCompiler** [umlet/umlet#475]
Since the uxf is just an XML file, I wrote a program to auto generate the XML contents from my data structures. 

But the problem with the current XML schema is that the association between an element with `<id>Relation</id>` and an element with `<id>UMLClass</id>` is implicitly deduced based on the locations of the elements. i.e. if the tip of the Relation (an arrow) touches the edge of the object (a box), then the program considers they're associated. e.g. auto snapping the arrow to the box and resize the arrow when I move the box.

But this could be problematic with auto generated XML contents since the generator may not have sophisticated way (as opposed to a human drawing on the screen) to prevent the edges of 2 different graphical elements to overlap which causes incorrect association. e.g. I often generates 2 boxes with edges overlapped and when another arrow is pointing at this overlapped edge, there is no simple way to deduce the association correctly.

Is it possible to have an XML  tag to explicitly specify which Relation is associated with which object instead of implicitly deducing this association based on overlapping x,y coordinates?

**Comment by afdia** [comment]
Hi

You're right there is no explicit association between elements in uxf files. UMLet also works based on overlapping positions, which means if you move an element, all relation ends which are positioned on the "sticking border" (most of the time the outer border) of the element will move at the same time.

There is no way to attach or detach relations from elements, it's just based on positions and unfortunately this cannot be changed without a major redesign of UMLet.
