### ISSUE TITLE
Build fails on assertion in test of out_newCustomElement.png

### ISSUE THREAD

**Issue by JoeyCorleone** [umlet/umlet#482]
After cloning the repo, I tried to build the project using `mvn clean install`.
The build fails due to an `AssertionError`:

~~~
batchConvertToPng_wildcardAndNoOutputParam_newCustomElement(com.baselet.standalone.MainBatchmodeTest)  Time elapsed: 0.097 sec  <<< FAILURE!
java.lang.AssertionError: The images /home/Desktop/test-uml/umlet/umlet-standalone/target/test-classes/com/baselet/standalone/out_newCustomElement.png and /tmp/junit7524420428649287861/junit693368850753612435.tmp.png don't match in the pixel (52/20)
	at org.junit.Assert.fail(Assert.java:88)
	at org.junit.Assert.assertTrue(Assert.java:41)
	at com.baselet.standalone.MainBatchmodeTest.assertImageEqual(MainBatchmodeTest.java:84)
	at com.baselet.standalone.MainBatchmodeTest.batchConvertToPng_wildcardAndNoOutputParam_newCustomElement(MainBatchmodeTest.java:61)
~~~
(Larger output here: https://gist.github.com/JoeyCorleone/de7bded60ebab26930dc39dd5abaab69 )

Skipping the tests with `-DskipTests` works and builds successfully.

**Comment by afdia** [comment]
Could you tell me your OS and Java version?
Unfortunately the svg output may differ between java versions which will result in test failures.
I can verify that the test is working on Win7+Oracle Java8 and on the Travis build server which uses oraclejdk8 (https://travis-ci.org/umlet/umlet)

**Comment by JoeyCorleone** [comment]
I'm running Debian 9:
~~~
Apache Maven 3.3.9
Maven home: /usr/share/maven
Java version: 1.8.0_151, vendor: Oracle Corporation
Java home: /usr/lib/jvm/java-8-openjdk-amd64/jre
Default locale: en_GB, platform encoding: UTF-8
OS name: "linux", version: "4.9.0-4-amd64", arch: "amd64", family: "unix"
~~~

**Comment by afdia** [comment]
Have you opened both images and checked if there are visible differences?
The path of both compared images is printed in the error message:
/home/Desktop/test-uml/umlet/umlet-standalone/target/test-classes/com/baselet/standalone/out_newCustomElement.png
/tmp/junit7524420428649287861/junit693368850753612435.tmp.png

If they look "the same", perhaps there is a better way to compare them other than pixel by pixel which could be used in the test

**Comment by JoeyCorleone** [comment]
Indeed, they pretty much look the same: [Image comparison](https://imgur.com/a/NF5uV)

They start to mismatch in pixel 52/20 in all runs.

**Comment by afdia** [comment]
I finally found the issue. Openjdk creates a slightly different output which causes the error.
I have added both pngs to the test output comparison as a quick fix and added openjdk in addition to oraclejdk to the travis build to make sure such issues are noted on the CI server

Thanks!
