### ISSUE TITLE
Cannot move activity all-in-one element

### ISSUE THREAD

**Issue by siro-mateos** [umlet/umlet#484]
I grab the "start" activity all-in-one from palette, and drop it into my diagram. It resizes automatically as I edit its contents, but I cannot grab it again to move it around.

**Comment by antanasb** [comment]
Hi, Siro-Mateos, it is intended behaviour. All-in-one diagrams are laid out automatically. If you like to move each element independently, please use non-all-in-one diagram elements.

**Comment by siro-mateos** [comment]
Yeah, but I'm not trying to move elements inside the activity diagram (activity states, transitions, forks, and so on) but the activity diagram as a whole (the big box with the "title: ") as an element in my general diagram... So I have a class diagram in which i've dropped an all-in-one activity diagram element to document some class method. I think I should be able to move this one around, although the sizing and contents were automatic...

**Comment by afdia** [comment]
You can move it around as a whole.
All in one diagrams behave like a larger single element which cannot be manually resized.

If there is a problem with moving elements around please describe a short sequence of actions to reproduce it

**Comment by siro-mateos** [comment]
This minimal UXF file reproduces the bug:

[CannotMoveActivityElement.zip](https://github.com/umlet/umlet/files/1557071/CannotMoveActivityElement.zip)

**Comment by antanasb** [comment]
@siro-mateos: thank you for the example. It clarifies the situation.
@afdia: I see the bug arise when both all-in-one diagram(s) and a _relation_element_ are placed in one file.

**Comment by afdia** [comment]
You are right the problem only occurs if a relation is on the same diagram as the activity all in one

I have found the error and fixed it for the next version. The fixed behavior is that relations may stick to the border of the all in one diagram (just like they do with the sequence all in one)
