### ISSUE TITLE
Palette not showing anything

### ISSUE THREAD

**Issue by modul** [umlet/umlet#486]
In umlet 14.1.1 and 14.2 on Windows 10, the palette shows up empty for me. See screenshot below …

Earlier versions work fine for me. In fact, I love umlet! :)

![umlet_1411](https://user-images.githubusercontent.com/700246/35562734-9c1209d6-05b4-11e8-932c-e00577121cc1.PNG)

**Comment by afdia** [comment]
Hi

This looks like umlet is having problems with reading the palettes directory. Are you sure it has the rights to read the palettes directory and its files?

To see some more log messages, you could also start umlet from the commandline using `java -jar umlet.jar` (the following image shows how it should look if no errors happen; you will probably see a stacktrace which may help to identify the problem)
![grafik](https://user-images.githubusercontent.com/8770707/35608294-c26ec386-0658-11e8-8dfd-1342c3f2fd2d.png)

**Comment by modul** [comment]
Thanks for the hint! It actually was a problem with the network path were I located Umlet. I always forget that UNC paths are a problem …
