### ISSUE TITLE
UI Rendering problem (partially visible text)

### ISSUE THREAD

**Issue by bloadvenro** [umlet/umlet#491]
Hello! Thank you for UMLet!

Recently I faced with some problem:
![image](https://user-images.githubusercontent.com/11679418/37214865-6816f534-23c7-11e8-868b-0983c68e76c1.png)
![image](https://user-images.githubusercontent.com/11679418/37214912-8d06c7ca-23c7-11e8-9520-8b76507a6f71.png)

My text is partially visible. Menus and options are also affected.

My system:
UMLet v14.2, Archlinux with i3wm desktop.

UMLet is the only one program in my userland with such behavior.

Thank you!

**Comment by antanasb** [comment]
I'm on Ubuntu 16.04 LTS and i3wm, java-8-openjdk-amd64. No such problem.

**Comment by bloadvenro** [comment]
@antanasb glad to hear! I thought the problem could be with i3wm

**Comment by bloadvenro** [comment]
The problem has gone after the recent system upgrade. At least I can see the content of my Open/Save dialog box :)

Now:
```
$ java -version
openjdk version "1.8.0_172"
OpenJDK Runtime Environment (build 1.8.0_172-b11)
OpenJDK 64-Bit Server VM (build 25.172-b11, mixed mode)
```

Also my intel video driver was updated.
