### ISSUE TITLE
No usage information shown while passing a wrong command line argument

### ISSUE THREAD

**Issue by barthel** [umlet/umlet#494]
If I start UMLet (v. 14.2, standalone) and passing an unknown command line argument, then UMLet ends quietly without showing the usage information.
```
$ java -Dsun.java2d.xrender=f -jar ./umlet.jar -foobar
2018-03-24 09:58:36,864 |      0 | INFO  | com.baselet.control.enums.Program | Initializing Program: Version=14.2, Runtime=STANDALONE
$
```

There is no possibility to show the usage information?
Using of ```--help```, ```-help```, ```-?```, ```-usage``` are ending in the behavior above.

The shell script ```umlet.sh``` uses all single command line arguments as a filename, so it is impossible to get usage information anyway.

**Comment by afdia** [comment]
Sounds reasonable, I have added -help and -usage which will print the message
```
USAGE: -action=convert -format=(pdf|svg|eps|bmp|jpg|wbmp|jpeg|png|gif) -filename=inputfile.uxf [-output=outputfile[.extension]]
```
(same message as mentioned in #493)
