### ISSUE TITLE
The umlet.sh should be tweaked.

### ISSUE THREAD

**Issue by barthel** [umlet/umlet#495]
The provided ```umlet.sh``` is not yet simple to adapt on different environments.

E.g.: I'm a macOS user and I don't like to have the Java icon in my application dock if UMLet is running:
![dock_umlet_java](https://user-images.githubusercontent.com/1170328/37862484-c4454ac2-2f4d-11e8-92ab-14b2b5d6c3ec.png)
With macOS specific Java start parameter (```-Xdock:name=Umlet -Xdock:icon=./img/umlet_logo.png```) it looks like this:
![dock_umlet_logo](https://user-images.githubusercontent.com/1170328/37862495-fc55b848-2f4d-11e8-8187-37b27248e3a8.png)
But this behavior could be possible with a os detection and enhancement of the shell script or via introducing a ```JAVA_OPTS``` or ```UMLET_JAVA_OPTS``` environment variable.

I also like to use the ```JAVA_HOME``` environment variable instead of make the ```java``` executable reachable in the ```PATH```.

Will such a pull request get a chance?

**Comment by afdia** [comment]
Hi
Improvements to the shell script are welcome, so please create a pull request.

If the change is backwards compatible we could change the current umlet.sh file and if it's not we could think about including a second script which improves the mac os case (we already have a windows specific exe so why shouldn't we have a mac os specific one)

And I agree that using JAVA_HOME is probably a good idea too.

**Comment by barthel** [comment]
@afdia Sounds good. I will prepare a PR for it.

It sounds, it will be reasonable and OK for you to add a Mac OS app (like the EXE)?

**Comment by afdia** [comment]
Thanks, with 

> Mac OS app

you mean a simple wrapper around `java -jar umlet.jar` right? I guess that would be a nice addition.

**Comment by barthel** [comment]
Yes. It's so called macOS Application Bundle. It's a kind of directory structure in a ```.app``` file.
There are two options.
1. Providing the App itself (like the EXE file)
2. Providing a installer like image (PKG or DMG file)

I'll take a look. But the tweaks helps a lot for now.

**Comment by afdia** [comment]
Sounds good, let me know if you have a working solution (I will not be able to test it though, because I don't have a computer with macOS available at the moment)

**Comment by barthel** [comment]
I'll create a new issue for the macOS app and copy/move the comments about into it.

The first step of tweaking the ```umlet.sh``` is done with #497.

**Comment by afdia** [comment]
good idea to keep the issues separated, I have added the milestone to this one
