### ISSUE TITLE
Creating new elements has become slow in 14.3

### ISSUE THREAD

**Issue by jderijke** [umlet/umlet#516]
Double clicking an element on the pallet (like simple class from the class palette),
it now takes about 2 seconds to appear in my diagram.
In 14.2 this is like instantaneous.
Please help me get back to fast modeling!
Windows 10, standalone version.

**Comment by jderijke** [comment]
Spot on.
My default java version "1.8.0_144"
But I do have 7, 9 and 10 installed

Both methods you mention solve the problem.

Thanks!

jan

**Comment by drake7707** [comment]
I noticed the same issue, double clicking a simple element liek "SimpleClass" takes a second or 2 in my (albeit large) diagram. Here's a [link](https://www.dropbox.com/s/yq7l91dvcgffqyk/fuse_ha_network.uxf?dl=1) to my uxf file. Open Umlet , open the diagram and then double click SimpleClass and you'll see a noticable delay.

**Comment by jderijke** [comment]
I only have Oracle JDK (8/9/10) installed, no OpenJDK, so I do not think the problem is with the distribution. Strange that the 14.3 .exe does not pick the system default jdk (i.e. 8).

**Comment by afdia** [comment]
You're right it's probably just the Java version. For whatever reason Java9+ seems to be much slower than 8 and older.

The runtime is chosen by Launch4J which we use to build the exe. It prefers JREs but uses JDKs if newer, and it prefers 64bit over 32bit.
I see no option to prefer the system default JRE, so I'm not sure if this would be possible.

Of course it's a problem if newer Java versions are slower and Launch4j prefers them over the better working Java8 runtime, but I guess we must investigate the performance problems and hopefully it's something we can fix in the umlet codebase

**Comment by afdia** [comment]
As nobody else mentions it and I don't really see it, I hope this is already fixed in newer Java versions

**Comment by jderijke** [comment]
runs OK in my current version (17), sorry for not getting back on this earlier.
