### ISSUE TITLE
Launcher shell script is broken on 14.3

### ISSUE THREAD

**Issue by fridtjof** [umlet/umlet#518]
When using the launcher with this command line in the UMLet directory:

./umlet.sh

and no special env vars set,

the following error occurs:
Error: Unable to access jarfile /umlet.jar

replacing line 31 with this line fixes the problem:

if [ ! -z "${UMLET_HOME}" ] ; then

I don't know if my test maybe behaves differently (i'm running macOS 10.13.6), so I thought I'd get some feedback first before opening a PR.

**Comment by afdia** [comment]
Hi
This has already been reported and fixed in #511 (the same way as you suggested)

Thanks!
