### ISSUE TITLE
Umlet 14.3 standalone, cannot start by running umlet.sh because of a wrong shell

### ISSUE THREAD

**Issue by stonenice** [umlet/umlet#528]
![image](https://user-images.githubusercontent.com/11694255/49284845-bd3bfc00-f4d0-11e8-9ad8-98aec85be136.png)

umlet.sh has a bug which relates not to start normally, and I suggest you to fix it.
Likes the follows:
--  before
if [ ! -x "${UMLET_HOME}" ] ; then
  _UMLET_HOME="${UMLET_HOME}"
fi

-- after
if [ ! -z "${UMLET_HOME}" ] ; then
  _UMLET_HOME="${UMLET_HOME}"
fi

or 

if [ ${#UMLET_HOME} -gt 0 ] ; then
  _UMLET_HOME="${UMLET_HOME}"
fi

**Comment by afdia** [comment]
Thanks, this will be fixed in the next version (see #511 )
