### ISSUE TITLE
ER Crow's foot notation

### ISSUE THREAD

**Issue by mnavarromugas** [umlet/umlet#532]
I dont know if it can draw that kind of diagram. It's missing the relations. Any idea?
![pict--crow s-foot-erd-design-elements-erd- crow s-foot-notation](https://user-images.githubusercontent.com/1218270/50672093-b5caaf80-0fb4-11e9-8d5f-6a32d8f2a167.png)

**Comment by afdia** [comment]
Currently only simple "crow foot arrows" are possible:

`lt=>-<`
![diagram 2019-01-04 09-30-51](https://user-images.githubusercontent.com/8770707/50679425-96a73e80-1003-11e9-91cd-666b6304dce1.png)

**Comment by paulsmithkc** [comment]
I've submitted code for the crows foot line endings, which are integrated for next release 😁

Currently there isn't a way to implement a 2 or 3 column diagram

**Comment by afdia** [comment]
for reference they have been implemented in #551

**Comment by paulsmithkc** [comment]
I seem to have forgotten the zero-to-one line ending, that should be an easy fix.

|o-

**Comment by mnavarromugas** [comment]
Excellent! Thanks
