### ISSUE TITLE
Cannot create/edit any custom element due to "java.lang.Object cannot be resolved"

### ISSUE THREAD

**Issue by leluna** [umlet/umlet#544]
Using version 14.3.0, I cannot create any new custom elements nor edit any existing ones. The Preview always show a list of errors stating that Object, String, Vector etc. cannot be resolved. 

![image](https://user-images.githubusercontent.com/12992462/57861643-3e751a00-77f7-11e9-9dd5-2e07844f7780.png)

Using customelement= in properties work just fine though.

**Comment by afdia** [comment]
You're right, I can reproduce the issue, but it also happens with older Umlet versions (I have tested 14.2 and 13.3)
So I guess it only occurs for certain Java versions, but I have to investigate more to find the cause of the problem

**Comment by afdia** [comment]
duplicates #546 and is fixed
