### ISSUE TITLE
Umlet 14.3 standalone opens and freezes on Windows Server 2012

### ISSUE THREAD

**Issue by NormBirkett** [umlet/umlet#545]
I am having this problem on two machines:
(1) One runs Windows Server 2012 Standard
(2) The other (a VM) runs Windows Server 2012 R2 Standard

Java version:
(1) java version "1.8.0_211"
Java(TM) SE Runtime Environment (build 1.8.0_211-b12)
Java HotSpot(TM) 64-Bit Server VM (build 25.211-b12, mixed mode)
(2) identical to (1) in every detail

Note that both machines have had Eclipse installed on them for months, maybe even a year or two. I don't use Eclipse, but it is part of my company's standard developer installation.

Umlet worked fine on both of these machines until a year or two ago. Many months, even years can go by between times when I use Umlet, so I don't know exactly when the problem started.  Machine (1) gets windows updates automatically; machine (2) does not--it's behind a firewall and has extremely limited internet access.

It is *possible* that the problem started when eclipse was installed.

Here's the problem: 
- I start Umlet either by clicking on the .exe file or the .jar file--same results both ways.
- The window opens right away, with just the frame populated--umlet symbol on the left, "UMLet - Free UML Tool for Fast UML Diagrams" in the middle, the minimize etc symbols on the right. Absolutely nothing inside the frame.
- If I reduce or maximize it, the menu bar appears. The menus display fine--but do absolutely nothing.
![image](https://user-images.githubusercontent.com/42503567/58816557-b87b1080-85f7-11e9-8506-bb43e08196bf.png)

I can't even exit--not even the "x" in the upper right corner works. So I have to kill the JVM process from Task Manager.

I'm wondering if the presence of eclipse on these machines could be hindering the standalone version of umlet from working. But that's just a speculative question.

My home desktop machine runs umlet just fine, so I usually end up doing my UML work on that, but that's not always convenient.

**Comment by afdia** [comment]
Hi
It looks like you're using standalone Umlet (not the Eclipse Plugin), so Eclipse shouldn't cause any problem.

To see errors or problems, you can try the following:

1. create a file called "log4j.properties" located in the Umlet directory with the following content:

```
# Logger setup for all loggers (all loggers inherit from rootLogger)
log4j.rootLogger=INFO, SYSTEM_OUT

# Appender SYSTEM_OUT writes to the console
log4j.appender.SYSTEM_OUT=org.apache.log4j.ConsoleAppender
log4j.appender.SYSTEM_OUT.layout=org.apache.log4j.PatternLayout
log4j.appender.SYSTEM_OUT.layout.ConversionPattern=%d{ISO8601} | %6r | %-5p | %-30c | %m%n
```

2. start a commandline, navigate to the Umlet directory and start umlet using:
```
java -Dlog4j.configuration=file:log4j.properties -jar umlet.jar
```

This will write additional logging information to the console which you can post here.

Without knowing further details, you can also try disabling File > Options > "Check for UMLet updates", because the check happens when umlet is started and it could cause problems behind a firewall.

Other that that, you can also try http://www.umletino.com/ which is a lightweight version of Umlet which runs in the browser. It can read/write the same uxf file format as Umlet, but has a slightly limited feature set (most noticable, it misses undo/redo of anything else than writing in a textbox)

**Comment by NormBirkett** [comment]
Added the logging properties file as you suggested. Here's what I see:

![image](https://user-images.githubusercontent.com/42503567/59046078-4ef53f00-884f-11e9-82e4-40e639058c85.png)

**Comment by NormBirkett** [comment]
I'm not sure how I could disable checking for updates from within Umlet, given that Umlet doesn't respond to any menu selections. Is there some config file that I could edit to achieve the same thing?

**Comment by afdia** [comment]
I'm not sure why it tries to split the -D parameter but try to quote it like:
`java "-Dlog4j.configuration=file:log4j.properties" -jar umlet.jar`

About the update check:
There should be a file: `C:\Users\<user>\AppData\Local\UMLet\umlet.cfg`. Make sure that it contains `check_for_updates=false`

**Comment by NormBirkett** [comment]
Thanks for all the help. Quoting the -D parameter worked.  When I started umlet, I got the following output down to "... 8 more". Then I chose File > Exit and got more output. Finally had to kill the java process from task manager.

![image](https://user-images.githubusercontent.com/42503567/59284350-1df38080-8c3a-11e9-8722-86b7e538e12d.png)

check_for_updates was previously set to true, but I've changed it to false--and the output above was generated with false.

**Comment by afdia** [comment]
The error says it cannot find a class which is located in umletdir/lib/rsyntaxtextarea-2.5.8.jar

Have you changed anything in your umlet installation or is it just the umlet.zip from www.umlet.com?

Maybe there are access restrictions and umlet cannot access the jar file.
Try starting umlet as administrator or make sure it has the rights to access all files in the umlet directory.

**Comment by NormBirkett** [comment]
Yes, I had installed by unzipping.

Strangely, that file you mention was completely missing, along with apparently one other file. I just downloaded the zip file again and did another extract all, and now everything is there and umlet is working for me again! Many, many thanks.

![image](https://user-images.githubusercontent.com/42503567/59557263-3c8fa980-8fa3-11e9-8ff9-6b54c71156d3.png)

Norm
