### ISSUE TITLE
Interpret relation position

### ISSUE THREAD

**Issue by rzfzr** [umlet/umlet#553]
Hello everyone, I'm working on a interpreter for umlet files, so that I can transform UML-ish diagrams into code (model driven development), doing the xml parsing is actually pretty easy, the only set back is trying to figure out what 2 elements are linked via a relation:
example, here are two relations, test1 and test2, they take the same positions, only thing that changes is the direction:
![image](https://user-images.githubusercontent.com/13456224/65265124-934ad900-dae6-11e9-9380-5034282f2847.png)
x, y, w, h of both is : 324,96,72,312
"additional_attributes" of test1 is 10,10,10,24, test2 is 10,240,10,10
it seems to me that it isn't very accurate... why does it start at 10? when the width is 72?

**Comment by afdia** [comment]
Hi
Typically on 100% zoom x,y,w,h should all be multiples of 10, if you zoom e.g. to 70%, they are multiples of 7.
We would have preferred to apply the zooming on a separate layer instead of directly manipulating coordinates, but it was too hard to fit into the existing application.

The relation points on the other hand are always calculated as if the zoom was 100%, so they don't change when you zoom in/out.

So for your usecase I would suggest to always zoom to 100% before doing anything, then you shouldn't have any problems with coordinates

**Comment by rzfzr** [comment]
Right, thanks, this helps for now.
However the umlet program itself can recreate the diagram regardless of zoom level (or does it scale to 100 first?) and it keeps track of what relation is pointing to who, so I should manage to recreate it....
Even at 100 zoom the values at the additional attributes does not match the same rect you get from x,y,w,h, maybe it has something to do with the size of the arrow or something.
My work in progress project in case someone is curious: https://github.com/GSEKM/PythonGenerator/blob/master/UMLet/umlet.py

**Comment by afdia** [comment]
It does the calculations at 100% zoom and the content of the additional attributes represent the coordinates of all relation points. It starts at (0,0) on the upper left corner of the relation element (it doesn't matter where it is placed on the diagram, so the element coordinates are irrelevant)

Here is one example (with activated grid and dev mode to make the coordinates easier to see):

The following relation
![grafik](https://user-images.githubusercontent.com/8770707/65346708-9c6aa180-dbdd-11e9-94f7-227968717b5c.png)

has `<additional_attributes>30.0;10.0;10.0;50.0</additional_attributes>`

The content is just a list of x1,y1,x2,y2,...

The first (upper) point is located at x=30 and y=10 (the grid shows one line every 10px, so you count 3 spaces to the right and one down)
The lower point is located at x=10 and y=50

As you can see it matches the image of the relation.

**Comment by rzfzr** [comment]
This is great,
thank you
