### ISSUE TITLE
How to let my NetBeans IDE to fect newer libs

### ISSUE THREAD

**Issue by chengm349** [umlet/umlet#559]
I noticed these lines that during building of the Eclipse Plugin project:

Fetching p2.index from http://download.eclipse.org/releases/mars/201506241002/
Fetching p2.index from http://download.eclipse.org/releases/mars/201506241002/
Fetching p2.index from http://download.eclipse.org/releases/mars/201510021000/
Fetching p2.index from http://download.eclipse.org/releases/mars/201510021000/
Fetching p2.index from http://download.eclipse.org/releases/mars/201602261000/
Fetching p2.index from http://download.eclipse.org/releases/mars/201602261000/

How to fetching newer libs automatically?

**Comment by afdia** [comment]
The links is from here: https://github.com/umlet/umlet/blob/master/umlet-eclipse-plugin/pom.xml#L16

But it's only used to build the plugin.jar. There is nothing Eclipse Mars specific in the output
