### ISSUE TITLE
org.eclipse.cdt.ui.internal.ui.wizards.NewClassCreationWizard.java

### ISSUE THREAD

**Issue by chengm349** [umlet/umlet#562]
I modified DiagramFileHandler in an added function which is to the effect:

JOptionPane.showMessageDialog( null, "generateAClass" );
NewClassCreationWizardPage page = new NewClassCreationWizardPage();
JOptionPane.showMessageDialog( null, classname );

I ran in Eclipse plugin mode and seems to me the plugin hang at new NewClassCreationWizardPage();

If I remove the 2nd line, I can see both prompts. Do I need to change plugin.xml under umlet-eclipse-plugin?

**Comment by chengm349** [comment]
public class NewClassCreationWizard extends NewElementWizard {
}

**Comment by ruspl-afed** [comment]
> NewClassCreationWizardPage page = new NewClassCreationWizardPage();
the WizardPage is designed to live inside the Wizard. Please have a closer look to the surrounding code, where should be a Wizard that instantiates this page. What you need to "emulate" the result of wizard work is the content of its "performFinish()" method.

**Comment by chengm349** [comment]
I changed code to:

JOptionPane.showMessageDialog( null, "generateAClass" );
NewClassCreationWizard page = new NewClassCreationWizard();
JOptionPane.showMessageDialog( null, classname );

But the same result (only see first showMessageDialog).

In fact I don't need Wizard popup window. I just need to have a simple way to create .h and .cpp files. If possible, please give me a almost there snipet.
