### ISSUE TITLE
Feature Request: Dark Mode

### ISSUE THREAD

**Issue by gerritwalther** [umlet/umlet#566]
It would be great if Umlet would get a dark mode. I have almost everything in dark mode except for Umlet and its always painful to switch to it.

**Comment by gerritwalther** [comment]
#414 might be related.

**Comment by eagle-te** [comment]
That would be nice :)

**Comment by afdia** [comment]
It's an interesting idea, but maybe not that easy with Umlet's draw panel which is mostly white (and we cannot really change that because diagram elements may be explicitly colored and visibility would be impaired if e.g. a blue foreground is on a gray or black diagram background)

**Comment by DevCharly** [comment]
If you guys are looking for a dark Swing L&F,
you could try FlatLaf (https://github.com/JFormDesigner/FlatLaf).
It comes with dark and light themes and scales on HiDPI screens.

**Comment by fedepeon** [comment]
To prevent my eyes from suffering on my Ubuntu I invert the color of the entire desktop

sudo apt install xcalib
xcalib -i -a

**Comment by afdia** [comment]
There will be a darkmode for the new VSCode plugin an Umletino.
Some changes will probably also help with a possible future implementation for Swing (e.g. [ThemeFactory](https://github.com/umlet/umlet/blob/master/umlet-elements/src/main/java/com/baselet/diagram/draw/helper/theme/ThemeFactory.java))

**Comment by afdia** [comment]
The next Umlet version will have a darkmode for standalone Umlet see #757
