### ISSUE TITLE
Unable to install umllet Eclipse plugin

### ISSUE THREAD

**Issue by walanqar** [umlet/umlet#579]
Hi,

I'm having a problem installing and using umlet.

I downloaded   com.umlet.plugin-14.2.jar   and adding it from Eclipse -> Help -> Install New Software

When adding it, I'm getting the error: Could not find jar file …  (Please see the attached screen shot)

The com.umlet.plugin-14.2.jar is saved in my Eclipse plugins folder

Umlet is not appearing in the wizard when I do file -> New -> Other

I'd appreciate your help.

I'm using:
  umlet 14.2
  Eclipse Version: 2018-09 (4.9.0), Build id: 20180917-1800
  Windows 10 64 bit

![umlet-eclipse-error](https://user-images.githubusercontent.com/62482130/80258981-8a108480-8652-11ea-999f-8b908f37b2d6.PNG)

**Comment by afdia** [comment]
Hi, please read https://github.com/umlet/umlet/wiki/Common-Problems#i-cannot-setupinstall-the-eclipse-plugin which should help you with the Eclipse setup

**Comment by walanqar** [comment]
Hi,

Thanks for the information.
I read it and tried couple things but it is still not working.
I'd appreciate your help as this is needed for my project and I can't proceed.

My Eclipse is a fresh installation, setup by my IT so it should be ok. I can't install it myself. I can't connect to umlet url either because of proxy restrictions. We download umlet from IT site.

The only install option for me I think is saving/unzipping com.umlet.plugin-14.2.jar and then do: "Help > Install New Software > Add > Local"

I noticed couple things that might be related:

1) In my Eclipse release, there is no Dropins folder but there is a Plugins folder

2) In the Location field (see attached screen), how the path should look?
file:/C:/APPS/Eclipse IDE 2018-09/plugins/com.umlet.plugin-14.2/
OR
file:/C:/APPS/Eclipse IDE 2018-09/plugins/com.umlet.plugin-14.2/com.umlet.plugin-14.2.jar
I tried both without success

![umlet-plugin-add](https://user-images.githubusercontent.com/62482130/80396788-2ae58680-8883-11ea-9389-217b0b45a509.PNG)

**Comment by afdia** [comment]
If you try to install it from a local repository you have to download the p2 repository from https://www.umlet.com/changes.htm (only available since umlet v14.3!) and unzip it
You should get a repository directory which can be used as location.
v14.2 doesnt have a repository so it cannot be installed that way

If you dont get it to work, you can also use Umlet standalone or www.umletino.com as alternatives

**Comment by walanqar** [comment]
Thanks! 
v14.3 (as mentioned above) worked
