### ISSUE TITLE
Group value

### ISSUE THREAD

**Issue by maqroll** [umlet/umlet#580]
Why group value is restricted to integers?

![Captura de pantalla 2020-04-27 a las 15 34 03](https://user-images.githubusercontent.com/415742/80378306-c20b0800-889c-11ea-955f-b15a3557b183.png)

I think would be more usable if you could assign names in the domain at hand.

Thanks!

**Comment by afdia** [comment]
If I remember correctly, grouping wasnt always visible in the properties, but only accessible by the contextmenu (select multiple elements and right click > group)
For this logic it just analyzes the highest used integer for the group and assigns this value +1

So automatic group assignment will always be an integer, but of course there could be manual groups which may use a more intuitive name.

I guess most people just group by using the context menu which is the reason nobody ever suggested custom group names.

**Comment by 911992** [comment]
#601 could be a fix for this.

Tests are appreciated.

**Comment by afdia** [comment]
Thanks for the fix @911992  (see #601)
I will close the issue
