### ISSUE TITLE
Is Wine the only way to install Umlet on Linux?

### ISSUE THREAD

**Issue by hunkjazz** [umlet/umlet#582]
I'm running Fedora 32 and looking for how to test Umlet directly on Linux.

All I need is a simple answer, so I can try to install it.

Sorry for the trouble, in advance!

**Comment by afdia** [comment]
Hi, Umlet is a Java based program so you just need a Java runtime to start it. Wine is not required.
Alternatively you can use it in your browser on www.umletino.com

**Comment by hunkjazz** [comment]
@afdia 

Thank you!

I just figured that all I needed to run was the jar file, thanks to you.
