### ISSUE TITLE
Saving diagram using (Ctrl+S) will set the caret position of working syntax pane at beginning(zero)

### ISSUE THREAD

**Issue by 911992** [umlet/umlet#594]
The problem(a little annoying) is about saving a diagram while editing an element's properties in syntax pane.

Once the file is saved, the caret position of the syntax pane goto the index zero(at the beginning), while the element is still selected in diagram(as expected)

This might be a little hard for people(devs mostly) like me who save too much(you know 2000 `ctrl+s` per minute is normal for devs), so for every `Ctrl + S`, the should be another caret positioning everytime.

I'm going to commit a change on related class (`OwnSyntaxPane`), to make it fix

How to produce the bug:  
* Open a new diagram
* add an an element, and change some properties
* save the diagram
    * Now the selected element is still selected
    * But the caret position of the properties pane is at index `0`(beginning)

**Comment by afdia** [comment]
Thanks for the report and the fix, it will be part of the next release
