### ISSUE TITLE
Disable Ctrl+Space for context-sensitive help

### ISSUE THREAD

**Issue by hsnotebook** [umlet/umlet#602]
I use Ctrl+Space to toggle my input method. How can I disable it in Umlet, or change the context-sensitive help to other shortkey?

**Comment by afdia** [comment]
unfortunately shortcuts are not customizable, so the only way would be changing the shortcut in the code and building a custom umlet version for yourself

**Comment by hsnotebook** [comment]
OK, and thank you for your response.
