### ISSUE TITLE
Use LGPL instead of GPL

### ISSUE THREAD

**Issue by Mogztter** [umlet/umlet#609]
Hello :wave: 

I'm working on a MIT-licensed project and I would like to use this library to render UMlet diagrams as images.
As far as I know, this won't be possible under GPL as I will need to license my project under GPL as well, correct?

I was wondering if you would consider to use a less restrictive license such as LGPL or Eclipse Public License?

Thanks!

**Comment by afdia** [comment]
Hi

I guess such a switch at this point in time would be very complicated as Umlet is years old and we have many contributions from different people, so we would have to contact them all or remove their code.

But I dont think it's necessary. I'm no expert in legal stuff, but I guess the GPL doesnt forbid you to create non-GPL output using a GPL program. A quick google search shows e.g. https://softwareengineering.stackexchange.com/questions/311084/using-output-of-gnu-gpl-software-in-commercial-purposes

Maybe someone else knows more details or has some reliable sources which can confirm this, but personally I'm quite sure that this should be no problem at all.

**Comment by Mogztter** [comment]
> But I dont think it's necessary. I'm no expert in legal stuff, but I guess the GPL doesnt forbid you to create non-GPL output using a GPL program. A quick google search shows e.g. softwareengineering.stackexchange.com/questions/311084/using-output-of-gnu-gpl-software-in-commercial-purposes

Sorry I wasn't clear, I'm actually using UMLet to render diagrams as part of my application.
Here's an example: 

<img src="https://kroki.io/umlet/svg/eNrdWUFv2jAYvedXRBym7lBiJ05ChEkvU7Ve1047VFNlEgNZQ4IcU8q_n51ip5SujRHNoAcwmCTye9_3vvfZWPjicZ7bD5RVWVmMerAPejYtkjLNiumo9_Pm8nzQu4jxcp5TfpdmZMrIPMY0p3Na8Bjz9YLGSTnv1xf0N_P9Malo_wfNCRdPxU59FU7KkonHEk6rGD_GoRdh5zHG6xgG2FnHeBW7noudVYxnsRsg7Mxi7GzdtCAFze8I5ywbL-VMzkdfcj48t1YzWpxViywVQGhRlWzUYyUXd_W-Ws44L5N7--lX7Ow8BJM0zeRCydY0DODQRWgoRw8NQ_UeipW9fgd2NC_vEZQsKy4mLwWy_Fqu8x8kDSKwIckNgGIJKJJAG47aI-aMFNWCMLHAa7HQRF4xmpC8ogdA3ColfIUWhgotDBRc6IVGOUEmnDL7DIJK5IC9ZxIgMIQADINADZL0Q4X_rch7SHGBXM0FUFygVqFfkYwfSfg3iL9nYmDrt4C7ngaOPn_KP0OryyD0FFzfrAoyWnHCDELuAlnUIJRDV4BDBdiLFOBoT7wLspSBaos2rNG6BwLbtoTrCo7A509nFCi78nU2Q6QKuKGpbxVwns1puTTIbV8ktrBvMYigR6jDDNeSFsJSJOgUr53NgARj3CK_oQ9qUatRToWgM-sKgSIg0vgHGj9ohZ8kCV1wa1wSedHUXpCqss7PLbEEtnZsJpYjQmEn4mcrLR313dTfXxUMZ8uu9OJrl4fPzM4340rnyq1kiRZToZpxWd7T9LdJu_uUJ-I1qD8NQFc1Q3d9rtaLKzcHTxxEe3NQlNycBxdGtVgiPXQlm6BxRl_rRluF34oGRv-IJN6WzSnZx0DLwdMUIHdPOYh2aJlzu5zYFSUsmRl0ClCKQLy7oPO2qNn5-GbdvsJtoHmvVrp7WGu4mTFKf5F169L3TPYn2Ri10DbUYINXwuu21DZJ7ZeGeBxW14IBBHYZ0E1BuxqfzKjYwuv63rQD9a5nI3LZDYzzrLi3czJfHBU9724VYNhsBj-_JBrbR_secEhJWI3hX307Rfiety980esWPJusGwpOyOvrg70XR5vIrCCYO56wuvBwhmcGE4IdmOHHwfT_F8ymedUwBx8HM-gYJto9oQ4HeyWtdftA8sxka-JFMnm97nYkTY2C_r41qjZtq4aa8fVx1eerQjymrSXDIz--c7b_o7P-At8zCQE="/>

The diagram text definition is encoded in the URL using a deflate + base64 algorithm:

https://kroki.io/umlet/svg/eNrdWUFv2jAYvedXRBym7lBiJ05ChEkvU7Ve1047VFNlEgNZQ4IcU8q_n51ip5SujRHNoAcwmCTye9_3vvfZWPjicZ7bD5RVWVmMerAPejYtkjLNiumo9_Pm8nzQu4jxcp5TfpdmZMrIPMY0p3Na8Bjz9YLGSTnv1xf0N_P9Malo_wfNCRdPxU59FU7KkonHEk6rGD_GoRdh5zHG6xgG2FnHeBW7noudVYxnsRsg7Mxi7GzdtCAFze8I5ywbL-VMzkdfcj48t1YzWpxViywVQGhRlWzUYyUXd_W-Ws44L5N7--lX7Ow8BJM0zeRCydY0DODQRWgoRw8NQ_UeipW9fgd2NC_vEZQsKy4mLwWy_Fqu8x8kDSKwIckNgGIJKJJAG47aI-aMFNWCMLHAa7HQRF4xmpC8ogdA3ColfIUWhgotDBRc6IVGOUEmnDL7DIJK5IC9ZxIgMIQADINADZL0Q4X_rch7SHGBXM0FUFygVqFfkYwfSfg3iL9nYmDrt4C7ngaOPn_KP0OryyD0FFzfrAoyWnHCDELuAlnUIJRDV4BDBdiLFOBoT7wLspSBaos2rNG6BwLbtoTrCo7A509nFCi78nU2Q6QKuKGpbxVwns1puTTIbV8ktrBvMYigR6jDDNeSFsJSJOgUr53NgARj3CK_oQ9qUatRToWgM-sKgSIg0vgHGj9ohZ8kCV1wa1wSedHUXpCqss7PLbEEtnZsJpYjQmEn4mcrLR313dTfXxUMZ8uu9OJrl4fPzM4340rnyq1kiRZToZpxWd7T9LdJu_uUJ-I1qD8NQFc1Q3d9rtaLKzcHTxxEe3NQlNycBxdGtVgiPXQlm6BxRl_rRluF34oGRv-IJN6WzSnZx0DLwdMUIHdPOYh2aJlzu5zYFSUsmRl0ClCKQLy7oPO2qNn5-GbdvsJtoHmvVrp7WGu4mTFKf5F169L3TPYn2Ri10DbUYINXwuu21DZJ7ZeGeBxW14IBBHYZ0E1BuxqfzKjYwuv63rQD9a5nI3LZDYzzrLi3czJfHBU9724VYNhsBj-_JBrbR_secEhJWI3hX307Rfiety980esWPJusGwpOyOvrg70XR5vIrCCYO56wuvBwhmcGE4IdmOHHwfT_F8ymedUwBx8HM-gYJto9oQ4HeyWtdftA8sxka-JFMnm97nYkTY2C_r41qjZtq4aa8fVx1eerQjymrSXDIz--c7b_o7P-At8zCQE=

> Maybe someone else knows more details or has some reliable sources which can confirm this, but personally I'm quite sure that this should be no problem at all.

I'm also not a license expert! :sweat_smile: 
But as far as I understand, kroki.io should be GPL since we are using UMLet as part of this service?

Full disclosure, Kroki is being integrated on GitLab.com to render diagrams and since GitLab Community Edition (CE) is licensed under the terms of the MIT License, I believe that they cannot add/use a service with a GPL license.

To be completely transparent, I wasn't aware of this potential issue until just now and I'm willing to remove UMLet from Kroki to comply with the license (if necessary).

**Comment by afdia** [comment]
Thans for the detailed information. That plugin sounds like a great idea to me and I would hate to see Umlet being dropped just because of licensing issues.
I cannot imagine that any umlet contributor thinks otherwise but a license change of umlet would be too much work (I have seen some projects who did that and its a huge amount of work and often takes years)

So I guess we should instead focus on the question whether it's possible to still use umlet despite the GPL.

According to https://www.gnu.org/licenses/gpl-faq.html#GPLModuleLicense

> If a programming language interpreter is released under the GPL, does that mean programs written to be interpreted by it must be under GPL-compatible licenses? (#IfInterpreterIsGPL)
> 
>     When the interpreter just interprets a language, the answer is no. The interpreted program, to the interpreter, is just data; a free software license like the GPL, based on copyright law, cannot limit what data you use the interpreter on. You can run it on any data (interpreted program), any way you like, and there are no requirements about licensing that data to anyone.
> 
>     However, when the interpreter is extended to provide “bindings” to other facilities (often, but not necessarily, libraries), the interpreted program is effectively linked to the facilities it uses through these bindings. So if these facilities are released under the GPL, the interpreted program that uses them must be released in a GPL-compatible way. The JNI or Java Native Interface is an example of such a binding mechanism; libraries that are accessed in this way are linked dynamically with the Java programs that call them. These libraries are also linked with the interpreter. If the interpreter is linked statically with these libraries, or if it is designed to link dynamically with these specific libraries, then it too needs to be released in a GPL-compatible way.
> 
>     Another similar and very common case is to provide libraries with the interpreter which are themselves interpreted. For instance, Perl comes with many Perl modules, and a Java implementation comes with many Java classes. These libraries and the programs that call them are always dynamically linked together.
> 
>     A consequence is that if you choose to use GPLed Perl modules or Java classes in your program, you must release the program in a GPL-compatible way, regardless of the license used in the Perl or Java interpreter that the combined Perl or Java program will run on. 

Another interesting point is https://www.gnu.org/licenses/gpl-faq.html#GPLOutput (maybe there are more FAQ entries for this usecase; I haven't checked all of them)

But I guess the basic idea is
- it's impossible to enforce the GPL on the input or output of umlet
- if you use umlet as a java depencency, you probably are required to release kroki under the GPL
- if you just call umlet in order to render a diagram, it should not be required to use the GPL for your own programm

The simplest way would be probably be using umlets batch mode e.g.:
`java -jar umlet.jar -action=convert -format=pdf -filename=C:/input.uxf -output=C:\`
Then you would not directly use java classes in your program but just call an "external umlet build" to interpret a uxf file.
This could be done by using the Java Process and Runtime API classes (like https://stackoverflow.com/questions/6780489/can-java-runtime-exec-another-java-program-that-uses-stdin )

I guess that should be fine, because it would be basically the same as if you create a webservice which expects an uxf file and returns a pdf. In both cases umlet would not be part of your program but just a tool you use to interpret uxf files.

You could even prompt users that they have to download umlet from www.umlet.com and place it at a specific location in order to interpret uxf files, if you want to avoid distribution of GPL umlet within your plugin (I don't think this would be a problem but then you would be 100% safe). Then users would also be able to upgrade or downgrade the used umlet version independently from the kroki version they use (just in case if there is a bug in a specific umlet version)

Again I'm not a laywer so this is no legal advice, but that is how I interpret the GPL and the FAQ from www.gnu.org

**Comment by Mogztter** [comment]
Many thanks for taking the time to gather information!
To be honest, I really don't get the reasoning, maybe it make sense in a GNU (compiler, C/C++) world but in Java I don't see the difference between:

- A Java program that calls `java -jar umlet.jar` to render a diagram (through Java Process Runtime API)
- A Java program that calls UMLet API to render a diagram (through classpath)

The only difference is that the jar is not in the same classpath but then the application is inside a Docker container so... 

I think the whole point is to avoid a proprietary software to build upon a GPL software by extending its capabilities. For instance, if I create a software based on UMLet but with additional syntax and/or a new rendering engine that would make sense that this software must be released under GPL.

If using the library "as-is" is allowed then I think that the whole bindings/linkings GNU jargon does not really apply in a JVM/Docker world.

> The simplest way would be probably be using umlets batch mode e.g.:
java -jar umlet.jar -action=convert -format=pdf -filename=C:/input.uxf -output=C:\
Then you would not directly use java classes in your program but just call an "external umlet build" to interpret a uxf file.
This could be done by using the Java Process and Runtime API classes (like stackoverflow.com/questions/6780489/can-java-runtime-exec-another-java-program-that-uses-stdin )

That could be a solution, yet not really efficient. Since I'm running server-side, I would like to avoid  executing `java` processes and writing files to disk.

> You could even prompt users that they have to download umlet from www.umlet.com and place it at a specific location in order to interpret uxf files, if you want to avoid distribution of GPL umlet within your plugin (I don't think this would be a problem but then you would be 100% safe). Then users would also be able to upgrade or downgrade the used umlet version independently from the kroki version they use (just in case if there is a bug in a specific umlet version)

Kroki is available as a fat-jar and a Docker image for ease of use.

```
$ java -jar kroki.jar
```
```
$ docker run -P8000:8000 yuzutech/kroki
```

The above commands will start a ready-to-use server on port 8000.


The FAQ is really interesting:

> Using the GNU GPL will require that all the released improved versions be free software. This means you can avoid the risk of having to compete with a proprietary modified version of your own work. However, in some special situations it can be better to use a more permissive license.

I don't think this is the case here, it's not a modified version of UMLet, it's UMLet + other diagram libraries behind a REST API.

But also:

> If a library is released under the GPL (not the LGPL), does that mean that **any software which uses it** has to be under the GPL or a GPL-compatible license? (#IfLibraryIsGPL)
**Yes, because the program actually links to the library.**
-- https://www.gnu.org/licenses/gpl-faq.en.html#IfLibraryIsGPL

This one is also interesting:

> When is a program and its plug-ins considered a single combined program? (#GPLPlugins)
It depends on how the main program invokes its plug-ins. If the main program uses fork and exec to invoke plug-ins, and they establish intimate communication by sharing complex data structures, or shipping complex data structures back and forth, that can make them one single combined program. A main program that uses simple fork and exec to invoke plug-ins and does not establish intimate communication between them results in the plug-ins being a separate program.
> If the main program dynamically links plug-ins, and they make function calls to each other and share data structures, we believe they form a single combined program, which must be treated as an extension of both the main program and the plug-ins. If the main program dynamically links plug-ins, but the communication between them is limited to invoking the ‘main’ function of the plug-in with some options and waiting for it to return, that is a borderline case.
> Using shared memory to communicate with complex data structures is pretty much equivalent to dynamic linking.
-- https://www.gnu.org/licenses/gpl-faq.en.html#GPLPlugins

I think this is a grey area, in this case Kroki is calling a single method `DiagramHandler.forExport(source)`:

https://github.com/yuzutech/kroki/blob/master/umlet/src/main/java/io/kroki/umlet/UmletConverter.java

I think I'm ready to go to the court with this one: 

> Can I release a nonfree program that's designed to load a GPL-covered plug-in? (#NFUseGPLPlugins)
Please see this question for determining when plug-ins and a main program are considered a single combined program and when they are considered separate programs.
If they form a single combined program then the main program must be released under the GPL or a GPL-compatible free software license, and the terms of the GPL must be followed when the main program is distributed for use with these plug-ins.
However, if they are separate works then the license of the plug-in makes no requirements about the main program.
See also the question I am writing free software that uses a nonfree library.
> -- https://www.gnu.org/licenses/gpl-faq.en.html#NFUseGPLPlugins

**Comment by afdia** [comment]
I would also say we can conclude this thread with
- switching license would be too complicated
- your usecase may be covered by the terms of GPL (up to interpretation but I cannot really add anything else than what I already said)

So if it's ok for you you can close the thread, and I will try to remember to try your plugin the next time I use on a project hosted on Gitlab because it seems quite nice and useful 👍 

Thanks!

**Comment by Mogztter** [comment]
Yes, this is a good summary, thanks for your help!
