### ISSUE TITLE
Umlet app for android

### ISSUE THREAD

**Issue by TheGreyDiamond** [umlet/umlet#610]
Is it possible to run Umlet on Android? Or is there already an umlet App which I didn't find?
I cant really use another software because its need to be file compatible.

**Comment by afdia** [comment]
Other than using umletino with its usability flaws on mobile devices, no there is not really an official umlet android port

**Comment by TheGreyDiamond** [comment]
Okay.

**Comment by afdia** [comment]
Just to be a bit more precise: www.umletino.com is a web based umlet app which has most of the features of standalone umlet. It works on any device, but the user interaction is still centered on keyboard+mouse, so using it on a small touch device like a phone is not the best experience (that's what I meant with "usability flaws").
We would have to redesign the way a user interacts with diagrams and see if we could find something that fits the typical touch based way of using a phone.

If you use a larger screen and/or mouse+keyboard like with an android notebook, the web based version should work perfectly fine for you.
