### ISSUE TITLE
VSCode plugin zoom is missing

### ISSUE THREAD

**Issue by yilativs** [umlet/umlet#611]
Please, add zoom option for VSCode plugin
Native VSecode ctrl+/- zoom in and out but it affect other panels.
Perhaps either different hot keys are needed for zooming only diagram panel, 
or at least zoom in/out in percentages combobox is needed same to what java application can do.

**Comment by afdia** [comment]
We are currently working on an improved zoom for vscode, so hopefully it should be finished soon!

**Comment by afdia** [comment]
this is part of umletino in v15 and the next vscode release (they currently use a different version schema)
