### ISSUE TITLE
VSCode Plugin: Tab key changing focus

### ISSUE THREAD

**Issue by kamatajinkya** [umlet/umlet#613]
I am trying to insert a `Tab` in the properties pane. When I hit the tab key, the focus changes to another pane instead of inserting an indent in the properties pane. This makes it impossible to create Package Diagrams.

I am using VSCode 1.52.0 on Ubuntu 20.04

**Comment by afdia** [comment]
Thanks for the report, you're correct this issue is also present in Umletino.

We will fix it in the next version (in the meantime you can copy&paste the tab symbol from the palette as a workaround)
