### ISSUE TITLE
Shell script in official download is still broken despite a fix commit from two years ago

### ISSUE THREAD

**Issue by ScrewTSW** [umlet/umlet#626]
https://github.com/umlet/umlet/commit/07e182758dccfd8580b26c12bc0b6a10ca30c467#commitcomment-47095062

When I downloaded the latest official build from your website and tried to run it, it was failing to set the correct `_UMLET_HOME` variable value, despite my `UMLET_HOME` being set in `~/.bashrc`

The check for variable still contains `-x` instead of `-z` in the if statement.

**Comment by afdia** [comment]
this has been fixed with the 15.0 release
