### ISSUE TITLE
class diagram palette: inner class

### ISSUE THREAD

**Issue by jderijke** [umlet/umlet#628]
i think the representation for inner classes in the class diagram is not correct. 
The nested class notation is imo for composition.
Inner class should look like a relation with line type 
lt=-(+)
![inner](https://user-images.githubusercontent.com/24924593/109564372-42178500-7ae1-11eb-9fb9-de60751b3989.png)

**Comment by afdia** [comment]
Hi, sorry for the late reply.

I guess you're talking about the following element?
![Diagram 2021-03-20 16-46-38 (1)](https://user-images.githubusercontent.com/8770707/111875802-ed5a8200-899b-11eb-84eb-9375eae2ff28.png)


I have not looked at the uml spec in a while but according to https://stackoverflow.com/a/57655130 both representations should be valid right?

**Comment by jderijke** [comment]
Well... i stand corrected.
I have always used the nested structure for composition, and examples in the spec to do that too (see below).
But the references the stackoverflow article you cite do support that the notation in the tool is correct.
Sorry for bringing this up...

![2021-03-20 17_34_37-Unified Modeling Language, v2 5 1 - Adobe Acrobat Pro DC (32-bit)](https://user-images.githubusercontent.com/24924593/111877816-5d213a80-89a5-11eb-90c7-5ac88497e7a7.png)
![image](https://user-images.githubusercontent.com/24924593/111877936-f6e8e780-89a5-11eb-9314-6c76ebbbe97a.png)
