### ISSUE TITLE
Compatibility with PlantUML syntax

### ISSUE THREAD

**Issue by huornlmj** [umlet/umlet#629]
I may have misunderstood the purpose of this tool.  But can it import or export PlantUML syntax, or is it simply a proprietary diagraming tool that does not use the PlantUML language syntax?

**Comment by afdia** [comment]
Umlet does not support PlantUML syntax but instead has its own text representation of diagams (uxf files).
Import of/Export to PlantUML sounds like an interesting feature , but it could only work for a very restricted set of diagrams. Umlet supports many customizations such as color changes, custom drawings within elements, non-uml elements, ... and it would be impossible to fit all of those into valid PlantUML diagrams.

**Comment by huornlmj** [comment]
ok - thanks for the clarification.  I thought it was a PlantUML editor.
