### ISSUE TITLE
When is umlet 14.4 or 15.0 coming?

### ISSUE THREAD

**Issue by eliroca** [umlet/umlet#631]
Hey there!

First thank you for UMLet! 

I was packaging UMLet for [openSUSE](https://www.opensuse.org) and noticed it hasn't got a release in quite a while.

https://www.umlet.com/changes.htm points to https://www.umlet.com/download/umlet_14_3/umlet-standalone-14.3.0.zip and this release doesn't include [this important fix](https://github.com/umlet/umlet/commit/07e182758dccfd8580b26c12bc0b6a10ca30c467).

I will just take the master branch here, but a newer release would be cleaner, hence the question.

**Comment by afdia** [comment]
Hi, you're right the last release has been a while as we have been focusing on the vscode plugin which got intermediate releases.

I would expect a release in the next few weeks, but the master branch should be working without any issues (and will be the source for the next release) so you can use it in the meantime.

**Comment by eliroca** [comment]
Thanks you, that's great!
