### ISSUE TITLE
bold text in notes

### ISSUE THREAD

**Issue by javgat** [umlet/umlet#635]
It would be awesome if notes could have words in bold text, like classes do surrounding the word with asterisks.
I write down OCL restrictions in notes and I would love to be able to have some words like "implies" in bold.

**Comment by afdia** [comment]
Do you mean the Note element?
![grafik](https://user-images.githubusercontent.com/8770707/112733118-56af3780-8f3e-11eb-8ae9-2a728f76f835.png)

If you start and end a line of text with * it will be shown in bold (this works for every element)
It doesnt work for single words if you are talking about that though

**Comment by javgat** [comment]
Oh yes, I was talking about that. Thank you, I didn't know that, my bad.

It would be great if single words were supported, but I understand that it could cause false-positives due to the usage of \* in UML.

**Comment by javgat** [comment]
Oh yes, I was talking about that. Thank you, I didn't know that, my bad.

It would be great if single words were supported, but I understand that it could cause false-positives due to the usage of \* in UML.
