### ISSUE TITLE
The Zoom droplist disappear on the toolbar

### ISSUE THREAD

**Issue by ahrtr** [umlet/umlet#636]
Previously I recall that I can zoom in/out the diagram, but I don't know why I can't see the Zoom drop-list on the toolbar now. Please see the attached screen shot. 

Detailed info:
- umlet version: 14.3.0
- MacOS version: 10.15.7
- Java Version: OpenJDK 15.0.1

<img width="1772" alt="Screen Shot 2021-03-31 at 9 57 16 PM" src="https://user-images.githubusercontent.com/30739825/113156355-7d39df00-926c-11eb-8418-137856b07799.png">

**Comment by afdia** [comment]
I don't know why it isn't showing (maybe it has to do with OSX, because on Windows I can see the toolbar)

Have you tried zooming using ctrl+mousewheel?

**Comment by ahrtr** [comment]
> I don't know why it isn't showing (maybe it has to do with OSX, because on Windows I can see the toolbar)
> 
> Have you tried zooming using ctrl+mousewheel?

I can zoom in/out using Ctrl  + Touchpad, but it isn't convenient. How can I make the Zoom Droplist visible on the toolbar?

**Comment by afdia** [comment]
It should be visible and the code for it has not been changed in a while, so I guess it's a problem with the way OSX integrates the Umlet menu into the top toolbar, but I cannot say for sure.
If I remember correctly this hasn't been reported before, so maybe you have a specific OS setting which causes the issue?

Maybe try an older Umlet version and see if it works?

**Comment by ahrtr** [comment]
@afdia Thanks for the quick response.

Yes, I upgraded my Mac OS recently, and the current Mac OS version is 10.15.7. Probably it's the reason, but I am not sure.

**Comment by ahrtr** [comment]
I just tried 14.2, and it works. I can see the Zoom droplist. It seems that this issue only applies to 14.3.

**Comment by afdia** [comment]
Thats weird, the class which adds the zoom panel is https://github.com/umlet/umlet/commits/master/umlet-standalone/src/main/java/com/baselet/standalone/gui/StandaloneGUIBuilder.java and it only had 1 change between 14.2 and 14.3 which shouldnt be the cause of the issue

Maybe try re-downloading 14.3 or check if you used another Java version to start 14.2 and 14.3? Unfortunately, as I cannot reproduce the issue it's hard for me to analyse the cause

**Comment by ahrtr** [comment]
I just downloaded the umlet-standalone-14.3.0.zip from https://www.umlet.com/download/umlet_14_3/umlet-standalone-14.3.0.zip, and ran into exactly the same issue. 

I used the same java version to start 14.2 and 14.3.  Please see the following info, 

$ java -version
openjdk version "15.0.1" 2020-10-20
OpenJDK Runtime Environment (build 15.0.1+9)
OpenJDK 64-Bit Server VM (build 15.0.1+9, mixed mode, sharing)

$ which java
/usr/local/opt/openjdk/bin/java

$ /usr/local/opt/openjdk/bin/java -version
openjdk version "15.0.1" 2020-10-20
OpenJDK Runtime Environment (build 15.0.1+9)
OpenJDK 64-Bit Server VM (build 15.0.1+9, mixed mode, sharing)

$ echo $UMLET_HOME
/Users/wachao/software/umlet

$ echo $JAVA_HOME
/usr/local/opt/openjdk`

**Comment by afdia** [comment]
unfortunately still not reproducible, maybe try the latest Umlet version?

**Comment by ahrtr** [comment]
Note that 15.0 and 15.1 still have this issue even I am using a new Mac book.  Only 14.2 works.
