### ISSUE TITLE
Port Project to Kotlin

### ISSUE THREAD

**Issue by SchoolGuy** [umlet/umlet#641]
Just as a thought... Kotlin is considered by some people the better Java. Thus I would kindly start a discussion if it would be of value to port this project to Kotlin.

In my eyes this would give the following benefits:

- NPEs are not possible per design if not explicitly allowed.
- Possible compilation to native machine code. --> This would mean the application has a better performance.
- Still fully compatible with Java (if compiled to JVM as a target).
- They claim you write less code in total because the language is "Concise" - https://kotlinlang.org/

Downsides/Things which need to be thought through: Doing UI is hard currently and if we mix too much Java into it, I wouldn't see the benefit of this huge amount of work. Still here is a list of resources for Kotlin UI topics: https://github.com/AAkira/Kotlin-Multiplatform-Libraries#gui

**Comment by afdia** [comment]
Hi!

Unfortunately it's impossible due to our dependency on GWT which required Java sourcecode.
Also there are many more Java developers and we would probably lose some potential contributions with such a switch

So its an interesting idea but not possible for Umlet.
