### ISSUE TITLE
Support for Java 11+

### ISSUE THREAD

**Issue by crlikcngroup** [umlet/umlet#643]
Hello,

First, UMLet is an awesome app! I was just wondering. Is there a plan to support Java 11 or higher?
I found myself in a situation where I can't or want to install Java 8 anymore and can't run UMLet at the moment. Should I wait for a new release or install Java 8?

Thank you

**Comment by afdia** [comment]
Hi

I use Umlet with Java11 all the time on Windows 10 with AdoptOpenJDK

Do you get an error?

**Comment by crlikcngroup** [comment]
Hm, yes. Maybe I will try to reinstall. Thank you!

![image](https://user-images.githubusercontent.com/46486968/115345867-b3a1b480-a1af-11eb-8289-023970acf152.png)

**Comment by afdia** [comment]
If it still cannot find your java installation try the current umlet.exe which should check more locations (see #548)

**Comment by crlikcngroup** [comment]
I deleted and downloaded UMLet again and now it works :)
But it only executes from JAR file. Windows .exe file still shows that error with JRE 1.6.0. Not sure if this is an issue.

Since the JAR works now I will close the issue.
Thank you!
