### ISSUE TITLE
umletino: Please prevent from losing unsaved diagrams

### ISSUE THREAD

**Issue by yangacer** [umlet/umlet#644]
Current web UI places [save] button above other saved disagrams, which potentially causes losing an unsaved (working) diagram if one clicked on those saved diagrams. I just saddly lost a 2-working-hours diagram.

Please consider to
- add a confirmation before loading saved disagrams if it will amend current diagram or
- place [save] button in somewhere away from those saved diagrams
either one of above will be helpful.

**Comment by afdia** [comment]
Hi

I agree, there should be a safety check to avoid losing the current diagram by doing one wrong click.

In the meantime I suggest to use ctrl+s to save the diagram (I always use the shortcut therefore the problem wasn't really obvious for me until now)

**Comment by yangacer** [comment]
Thank you for the ctrl+s tip and prompt fix!
