### ISSUE TITLE
VSCode Plugin, doesn't showing any window

### ISSUE THREAD

**Issue by joaobdm** [umlet/umlet#647]
After a sucessful plugin install, i create a blank .uxf file and nothing at all happens. I tried to reinstalling, disable all other plugins looking for any incompatibility, and other little things. Any of those worked for me. After that a booted on Manjaro Linux and installed the plugin and worked just fine out of the box. I would like to use the extension smooth as i use it on Linux.

Does not worked:
OS: Windows 10; VSCode version: 1.56.0

Worked:
OS: Manjaro Linux 21.0.4; VSCode (Flatpak) version: 1.55.2

**Comment by marina-sam14** [comment]
I have the same issue with Windows 10. I tweeted in UMLet and they told me to wait until this weekend for an update and after that, if the issue remains,we eill get in touch.

**Comment by marina-sam14** [comment]
I have the same issue with Windows 10. I tweeted toUMLet and they told me to wait until this weekend for an update and after that, if the issue remains,we will get in touch.

**Comment by Hichoow** [comment]
You should downgrade your visual studio code to 1.55. This error only occurs on 1.56 as it seems

**Comment by afdia** [comment]
thanks for the report, this is the same problem as in #647
we are trying to find a fix for the issue. there has been some changes within vscode which caused the umlet extension to break with 1.5.6

**Comment by afdia** [comment]
should be fixed already
