### ISSUE TITLE
UMLet corrupts old documents

### ISSUE THREAD

**Issue by lefty2** [umlet/umlet#652]
When I open a document created by umlet it now says "depreciated element will soon be removed" on all my classes. Can you stop it doing that?

**Comment by afdia** [comment]
Your diagram is using very old deprecated umlet elements (the new ones where introduced in v13 almost 7 years ago).
We try to keep those elements around in our codebase to keep old diagrams working but at one point we will probably have to remove them, therefore we show the warning for them.
If you don't want to migrate the elements and dont want to see the warning you could use an older version of Umlet

Information about migrating the elements from #233 is here:
https://github.com/umlet/umlet/wiki/Common-Problems#how-can-i-convert-deprecated-elements-red-background-and-deprecation-text-when-selected-to-the-non-deprecated-ones
