### ISSUE TITLE
How to move object by a pixel

### ISSUE THREAD

**Issue by q0987** [umlet/umlet#654]
Hello,

I tried to move an object by pixel horizontal or vertical but it always jumps up or down, left or right and doesn't allow me to move only for a pixel distance.

Is there a way that I can move the object slightly?

Thank you

**Comment by afdia** [comment]
Hi
I hope I understand your question correctly but Umlet at 100% zoom allows only movement in 10px increments. At 90% zoom it's 9px and so on

**Comment by hadi4172** [comment]
You can open the uxf file as a text file and change the value manually

**Comment by afdia** [comment]
That's true but I would not suggest to do that because your diagram could behave in weird ways due to the impossible state (e.g. relation sticking and zooming could be broken)

**Comment by q0987** [comment]
It would be nice if we can move the object by 1 pixel with 100% zoom.
