### ISSUE TITLE
conversion from old diagram file format to new format

### ISSUE THREAD

**Issue by Nevebranca** [umlet/umlet#657]
Opening an old diagram, UMLet says "depreciated element will soon be removed" on all element in class diagrams. Even to store the diagram file doesn't help. Can you please provide a conversion into the new file format?

**Comment by afdia** [comment]
Hi, there is no conversion tool but for most elements a conversion using any texteditor should be simple.
Please read https://github.com/umlet/umlet/wiki/Common-Problems#how-can-i-convert-deprecated-elements-red-background-and-deprecation-text-when-selected-to-the-non-deprecated-ones
