### ISSUE TITLE
Crashes on eclipse

### ISSUE THREAD

**Issue by mj8w** [umlet/umlet#667]
Eclipse 21-12 On Ubuntu20.04

Crashes when loading existing .uxf file from project.

Unspecified error [Error while starting AWT] (java.lang.UnsatisfiedLinkError: Could not load SWT library. Reasons: 
	/home/mikew/apps/eclipse/eclipse/configuration/org.eclipse.osgi/892/0/.cp/libswt-awt-gtk-4948r9.so: /home/mikew/.p2/pool/plugins/org.eclipse.justj.openjdk.hotspot.jre.full.linux.x86_64_16.0.2.v20210721-1149/jre/lib/libjawt.so: version `SUNWprivate_1.1' not found (required by /home/mikew/apps/eclipse/eclipse/configuration/org.eclipse.osgi/892/0/.cp/libswt-awt-gtk-4948r9.so)
	no swt-awt-gtk in java.library.path: /usr/java/packages/lib:/usr/lib64:/lib64:/lib:/usr/lib
	no swt-awt in java.library.path: /usr/java/packages/lib:/usr/lib64:/lib64:/lib:/usr/lib
	/home/mikew/.swt/lib/linux/x86_64/libswt-awt-gtk-4948r9.so: /home/mikew/.p2/pool/plugins/org.eclipse.justj.openjdk.hotspot.jre.full.linux.x86_64_16.0.2.v20210721-1149/jre/lib/libjawt.so: version `SUNWprivate_1.1' not found (required by /home/mikew/.swt/lib/linux/x86_64/libswt-awt-gtk-4948r9.so)
	Can't load library: /home/mikew/.swt/lib/linux/x86_64/libswt-awt-gtk.so
	Can't load library: /home/mikew/.swt/lib/linux/x86_64/libswt-awt.so
	/home/mikew/.swt/lib/linux/x86_64/libswt-awt-gtk-4948r9.so: /home/mikew/.p2/pool/plugins/org.eclipse.justj.openjdk.hotspot.jre.full.linux.x86_64_16.0.2.v20210721-1149/jre/lib/libjawt.so: version `SUNWprivate_1.1' not found (required by /home/mikew/.swt/lib/linux/x86_64/libswt-awt-gtk-4948r9.so)
)

**Comment by afdia** [comment]
Hi

When searching for the problem I have found
https://stackoverflow.com/questions/66760572/eclipse-javase-1-8-version-sunwprivate-1-1-not-found
https://github.com/libgdx/libgdx/issues/5996

So I guess it has to do with the Java version you are using to start Eclipse. According to the comment from the stackoverflow url the Java version which is integrated into Eclipse may not work, so maybe try another Java distribution? Like https://adoptopenjdk.net/ (or any other from the Ubuntu repo?)
