### ISSUE TITLE
Option to export `.uxf` diagram as image in VS Code extension

### ISSUE THREAD

**Issue by cr2007** [umlet/umlet#671]
I was using the VS Code extension of [UMLet](https://marketplace.visualstudio.com/items?itemName=TheUMLetTeam.umlet), and I was wondering if there was an in-built option in the extension to export the diagrams as an image (`.jpg`, `.png`, etc.).

Currently, the only way I use to take it as a screenshot, but that might be a problem as the diagram expands, when it can get a lot pixelated.

So I was wondering if there was any option to export the UML diagrams via the [VS Code Extension](https://marketplace.visualstudio.com/items?itemName=TheUMLetTeam.umlet).

**Comment by afdia** [comment]
Hi , you can use ctrl+shift+p and select "Umlet export as PNG" to export it as png.

**Comment by cr2007** [comment]
Oh, this is wonderful
Thank you so much for this!!

This extension is truly a lifesaver! 🙏

**Comment by afdia** [comment]
Thanks! :)
