### ISSUE TITLE
BrowserLauncher.java | Launch browser with xdg-open on linux

### ISSUE THREAD

**Issue by digidigital** [umlet/umlet#673]
I try to pack the .jar file in a snap package for the Ubuntu snap store.

Everything works fine except for opening links since (for some reason Desktop.browse is not supported and the fallback solution in BrowserLauncher.java does not work in the confined environment).

`ERROR Error at opening the URL.
java.lang.UnsupportedOperationException: The BROWSE action is not supported on the current platform!
 at java.desktop/java.awt.Desktop.checkActionSupport(Desktop.java:380)
 at java.desktop/java.awt.Desktop.browse(Desktop.java:524)
 at com.baselet.gui.BrowserLauncher.openURL(BrowserLauncher.java:26)`

The fallback solution for this case seems to try various browsers out of a list.

Wouldn't it be more robust to just call xdg-open, since it is supported by almost all modern Linuxes and takes care of browser selection?
See "Solution 2": https://stackoverflow.com/a/70434441
(Solution 1 is no real option since libgnome-2-0 is no longer available for e. g. Ubuntu 20.04+)

**Comment by digidigital** [comment]
Another issue with the code seems to be that:

Desktop.isDesktopSupported() returns True and then desktop.browse(new URI(url)) throws the exception.
The alternative "// Only if desktop is not supported we try the old main specific code" is not reached because it is within the try block.

Otherwise I would have been able to work around the issue by creating a symlink "firefox" that redirects to xdg-open :)

**Comment by afdia** [comment]
Hi

You're right that the fallback was not flexible enough. I have changed the bit and included the xdg-open option before trying different browsers.

You can check the linked commit and try it out with the latest build if you want (as soon as it finishes) https://github.com/umlet/umlet/actions/runs/2149526984

**Comment by digidigital** [comment]
Tested with Ubuntu 20.04

Case 1 - "Normal use"      -> Execute umlet.sh after unzipping, click on links and Help menu items, browse websites
Case 2 - "Snap Package" -> Put everything in SNAP Package and execute installed snap, click on links and Help menu items, browse websites

Works like a charm!  👍🏼
