### ISSUE TITLE
Crash when dragging one arrow-end on top of arrow-start (or vice versa)

### ISSUE THREAD

**Issue by i0xHeX** [umlet/umlet#679]
**Details:**
UMLet 15.0.0 Standalone
JDK 17.0.3.1

**Reproduce steps:**
- Open UMLet
- Drag any type of arrow from templates to the working space
- Drag one arrow-end on top of another

**Video:**
https://youtu.be/6E6iH5CjZQQ

_P.S. There is no such issue in earlier version 14.3.0_

**Comment by afdia** [comment]
Thanks for the report! At first I though its the JDK as in #523 but this was a new issue caused by the changes of #608
