### ISSUE TITLE
Properties pane strange behaviour: focus much higher than the font size

### ISSUE THREAD

**Issue by jmcroset** [umlet/umlet#681]
Hi!

No idea how to fix this: tried fontsize setting of properties pane to no avail, stays like 200px. When selecting text, said text simply disappears...
Thanks for any hint.

OS is Manjaro, UMLet 15.0.0

![image](https://user-images.githubusercontent.com/107713802/174356807-a6b99b0a-e482-4dbc-aca5-d86c695fbe37.png)

**Comment by afdia** [comment]
Hi. Just to get it right:
You mean that if you click into any line of the properties panel (which highlights the background of the line yellow), the area the line and therefore the yellow highlighting uses is too much (200px height), right?

So in fact every line of text occupies 200px of space, is that correct?

I have never heard about that behavior. Was it already present in v14.3? We updated the version of the rsyntaxtextarea lib which we use to display the properties text, maybe that introduced an issue.

**Comment by jmcroset** [comment]
That's correct, the line height is much, much higher than the font size. The issue is only on this specific machine, on another one with the same OS and version 15.0.0, the behaviour is just fine.

Can it have something to do with the font configuration of the OS ? Could you point out any potential settings / conf files to check, that may lead to the issue ?

**Comment by afdia** [comment]
I would suggest to check the Java version you use on both machines and try the version from the machine where it works.

Maybe it could also be the OS font configuration, but I have never heard of such a behavior

You could also try the previous Umlet version 14.3 just to see if it behaves the same. Or if nothing else fixes the issue you could use www.umletino.com which has most of the features of standalone umlet.

Other than that I don't really have an idea what could cause this behavior
