### ISSUE TITLE
vscode extension v1.0.5 is not available on marketplace

### ISSUE THREAD

**Issue by beppemarazzi** [umlet/umlet#682]
reading at https://github.com/umlet/umlet/blob/master/umlet-vscode/CHANGELOG.md there is a v1.0.5 available... but on marketplace https://marketplace.visualstudio.com/items?itemName=TheUMLetTeam.umlet the last release is v1.0.4
Any chance to publish it?

Many thanks

**Comment by afdia** [comment]
Thanks for the report!
You're right, we missed the vscode plugin because until now the versions where disjoint.
We will deploy it to the marketplace in the next few days and from this release on the versions will be synchronized (so the vscode plugin will also be called v15)

**Comment by beppemarazzi** [comment]
Closing the issue: just found the new version (15.0.0) on the marketplace (published on 7/10/2022).

Many thanks again
