### ISSUE TITLE
mouse dragging bugs

### ISSUE THREAD

**Issue by katzda** [umlet/umlet#688]
My system is PopOs.

Arrows sometimes don't line up:

![image](https://user-images.githubusercontent.com/12850106/190432494-98bde42d-88cc-4e41-8638-da93ccce43a2.png)

When dragging arrows by the middle square, often the arrow breaks in half or simply completely ignores that I'm trying to drag and stays in place so I need multiple attempts to maybe hit the right spot or something, which is annoying.

Similar problem when dragging by the ends, very bad experience!

**Comment by afdia** [comment]
Hi, that is weird, are you using the latest version (15.0) of Umlet or are you opening an old diagram which may already have some misaligned elements?
In previous versions we had issues with the grid alignment of elements (if I remember correctly zooming to extremes like 10% was sometimes misaligning elements), but as far as I know these bugs should have been fixed.

Maybe try zooming in and out, this should usually align elements to the grid.

**Comment by katzda** [comment]
I tried
sudo apt update
sudo apt install umlet

`umlet is already the newest version (13.3-1.3).`

**Comment by afdia** [comment]
I see, v13.3 is 7 years old and I'm quite sure that it still had the problems with alignment

As we don't control the apt packages and cannot tell you when or if it will ever be updated, I would suggest to download Umlet v15 package from https://www.umlet.com/changes.htm or use the web-based version https://www.umletino.com/

Both should have no problem with alignment

**Comment by katzda** [comment]
Thanks that makes sense, I forgot it's java.

**Comment by katzda** [comment]
So I updated to version 15, and the mouse dragging is no longer an issue but funnily, I still can see the misalignment against the grid as in my screenshot. Not sure if there is a trick to it, I tried to `save as` and reopen, extreme zoom in, save, extreme zoom out, save.. didn't help.

<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<diagram program="umlet" version="15.0.0">
  <zoom_level>10</zoom_level>
  <element>
    <id>UMLClass</id>
    <coordinates>
      <x>50</x>
      <y>60</y>
      <w>60</w>
      <h>60</h>
    </coordinates>
    <panel_attributes>Class1
style=autoresize
--
hello
--</panel_attributes>
    <additional_attributes/>
  </element>
  <element>
    <id>Relation</id>
    <coordinates>
      <x>80</x>
      <y>100</y>
      <w>30</w>
      <h>80</h>
    </coordinates>
    <panel_attributes>lt=&lt;-</panel_attributes>
    <additional_attributes>10.0;15.0;10.0;65.0</additional_attributes>
  </element>
  <element>
    <id>UMLClass</id>
    <coordinates>
      <x>50</x>
      <y>170</y>
      <w>60</w>
      <h>60</h>
    </coordinates>
    <panel_attributes>Class2
style=autoresize
--
hello
--</panel_attributes>
    <additional_attributes/>
  </element>
</diagram>

**Comment by katzda** [comment]
Ok, it's just a problem with some elements. Some are not misaligned, and so I used those instead.

**Comment by afdia** [comment]
The part
`<additional_attributes>10.0;15.0;10.0;65.0</additional_attributes>`
defines the points of the relation. At 100% zoom every coordinate must be dividable by 10, so 15 and 65 should not be possible.

I guess this is a diagram created by v13.3 right? It should not be possible to create such a relation by using a newer Umlet version, but you are right that relations don't auto-fix themselves by zooming.

So I would suggest to create a new diagram which should not have these issues or you change 15 to 20 and 65 to 70. After that the relation should remain on the grid

**Comment by katzda** [comment]
thanks I think you can close this issue, sorry for bothering.

**Comment by afdia** [comment]
You're welcome!
