### ISSUE TITLE
VScode Extension - not working

### ISSUE THREAD

**Issue by scrolls5** [umlet/umlet#693]
In VScode it gives me this error:
**Sorry, the program just crashed. Please check logs and report a bug.**
when opening a .uxf file in VScode with the umlet extension.

**Comment by scrolls5** [comment]
Hi,

Extension host gives me this:
UMLet|2022-11-14 19:02:58|error|Script error. (:0)

**Comment by afdia** [comment]
Does the developer tools console show additional logs?

Maybe try to uninstall the extension and install it again "manually" by going to https://marketplace.visualstudio.com/items?itemName=TheUMLetTeam.umlet clicking "Download Extension" and dragging it into the extension column in vscode. Maybe that helps?

Other than that I cannot really imagine what causes the error. Could you please tell us the vscode version and your OS?

**Comment by scrolls5** [comment]
It looks like a theme extension I was using for VScode was interfering with the UMLET extenstion. solved by disabling the theme extension.

Thank you for your time and effort 🗡️

**Comment by afdia** [comment]
Glad to hear that and thanks for telling us, it may help others with comflicting extensions
