### ISSUE TITLE
umlet 15 freeze: java.lang.NullPointerException: Cannot read field "x" because "center" is null

### ISSUE THREAD

**Issue by jderijke** [umlet/umlet#699]
Open the attached diagram, select sharepointCalculator and type return in it properties.
Umlet freeses with the above error.
This works OK in umlet 14.3.
======
java.lang.NullPointerException: Cannot read field "x" because "center" is null
Exception in thread "AWT-EventQueue-0" java.lang.NullPointerException: Cannot read field "x" because "center" is null
        at com.baselet.element.relation.helper.RelationPointList.getDragBox(RelationPointList.java:183)
        at com.baselet.element.relation.helper.RelationPointHandler.getDragBox(RelationPointHandler.java:144)
        at com.baselet.element.relation.helper.RelationPointHandler.isPointOverDragBox(RelationPointHandler.java:81)
        at com.baselet.element.relation.helper.RelationPointHandler.getSelection(RelationPointHandler.java:34)
        at com.baselet.element.relation.Relation.isSelectableOn(Relation.java:131)
        at com.baselet.element.ComponentSwing.contains(ComponentSwing.java:73)
        at java.desktop/java.awt.Container.findComponentAtImpl(Container.java:2713)
        at java.desktop/java.awt.Container.getChildAt(Container.java:2739)
        at java.desktop/java.awt.Container.findComponentAtImpl(Container.java:2725)
        at java.desktop/java.awt.Container.getChildAt(Container.java:2739)

==== domein_klasse.uxf =====
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<diagram program="umlet" version="14.3.0">
  <zoom_level>10</zoom_level>
  <element>
    <id>UMLClass</id>
    <coordinates>
      <x>120</x>
      <y>180</y>
      <w>210</w>
      <h>90</h>
    </coordinates>
    <panel_attributes>Gebruiker
--
-login: String
-locatie: GeoLocatie
-sharepoints: long</panel_attributes>
    <additional_attributes/>
  </element>
  <element>
    <id>UMLClass</id>
    <coordinates>
      <x>430</x>
      <y>100</y>
      <w>500</w>
      <h>260</h>
    </coordinates>
    <panel_attributes>&lt;&lt;Entity&gt;&gt;
/Gereedschap/
--
-id: integer
-beschrijving: String
--
getWaarborg()
/getDagPrijs()/
gereedschapsTypeGoedGekeurd
zetBeschikbaar()
zetOnbeschikbaar()
goedgekeurd()
afgekeurrd()
aanvraagHerkeuring()
-setStatus(allowedStates:GereedschapStatus[*], newState:GereedschapStatus
-setStatus(allowedState:GereedschapStatus, newState:GereedschapStatus</panel_attributes>
    <additional_attributes/>
  </element>
  <element>
    <id>UMLClass</id>
    <coordinates>
      <x>1000</x>
      <y>270</y>
      <w>150</w>
      <h>90</h>
    </coordinates>
    <panel_attributes>GereedschapsType
--
-waarborg: long
-naam: String</panel_attributes>
    <additional_attributes/>
  </element>
  <element>
    <id>UMLClass</id>
    <coordinates>
      <x>570</x>
      <y>540</y>
      <w>260</w>
      <h>210</h>
    </coordinates>
    <panel_attributes>style=autoresize
&lt;&lt;Entity&gt;&gt;
Reservatie
--
id: int
-periode: Periode
--
isIn(:datum)
isAfhaalbaar(:datum)
getStatus():
getPrijs()
getAnnulatievergoeding()
getStatusType():ReservatieStatusType
</panel_attributes>
    <additional_attributes/>
  </element>
  <element>
    <id>Relation</id>
    <coordinates>
      <x>920</x>
      <y>310</y>
      <w>100</w>
      <h>40</h>
    </coordinates>
    <panel_attributes>lt=&lt;-
m2=*</panel_attributes>
    <additional_attributes>80.0;10.0;10.0;10.0</additional_attributes>
  </element>
  <element>
    <id>Relation</id>
    <coordinates>
      <x>320</x>
      <y>220</y>
      <w>130</w>
      <h>50</h>
    </coordinates>
    <panel_attributes>lt=&lt;-
m2=*
r1=aanbieder
</panel_attributes>
    <additional_attributes>10.0;20.0;110.0;20.0</additional_attributes>
  </element>
  <element>
    <id>Relation</id>
    <coordinates>
      <x>610</x>
      <y>350</y>
      <w>40</w>
      <h>210</h>
    </coordinates>
    <panel_attributes>lt=-
m2=*
m1=1</panel_attributes>
    <additional_attributes>10.0;10.0;10.0;190.0</additional_attributes>
  </element>
  <element>
    <id>Relation</id>
    <coordinates>
      <x>290</x>
      <y>260</y>
      <w>330</w>
      <h>300</h>
    </coordinates>
    <panel_attributes>lt=-
m2=*
r1=ontlener</panel_attributes>
    <additional_attributes>10.0;10.0;10.0;120.0;310.0;120.0;310.0;280.0</additional_attributes>
  </element>
  <element>
    <id>Relation</id>
    <coordinates>
      <x>920</x>
      <y>90</y>
      <w>100</w>
      <h>50</h>
    </coordinates>
    <panel_attributes>lt=&lt;&lt;&lt;&lt;-&gt;
m2=*
bestaat uit</panel_attributes>
    <additional_attributes>80.0;20.0;10.0;20.0</additional_attributes>
  </element>
  <element>
    <id>UMLClass</id>
    <coordinates>
      <x>60</x>
      <y>470</y>
      <w>390</w>
      <h>210</h>
    </coordinates>
    <panel_attributes>style=autoresize
&lt;&lt;aggregate&gt;&gt;
Transactie
--
id: int
-tijdstip: DateTime
/sharepoints: long
-status:{onbevestigd,bevestigd}
--
addReservatieTransacaties
(:Reservatie,  ReservatieStatusType)
addLijn(:TransactieLijn)
addLijn
(:Reservatie, :ReservatieTransactieLijnType, bedrag:double) </panel_attributes>
    <additional_attributes/>
  </element>
  <element>
    <id>Relation</id>
    <coordinates>
      <x>820</x>
      <y>700</y>
      <w>150</w>
      <h>50</h>
    </coordinates>
    <panel_attributes>lt=&lt;-&gt;&gt;&gt;&gt;&gt;
m1=1..*
m2=
r1=historiek</panel_attributes>
    <additional_attributes>130.0;20.0;10.0;20.0</additional_attributes>
  </element>
  <element>
    <id>UMLClass</id>
    <coordinates>
      <x>270</x>
      <y>750</y>
      <w>120</w>
      <h>70</h>
    </coordinates>
    <panel_attributes>style=autoresize
&lt;&lt;aggregate&gt;&gt;
/TransactieLijn/
--
sharepoints: long</panel_attributes>
    <additional_attributes/>
  </element>
  <element>
    <id>Relation</id>
    <coordinates>
      <x>130</x>
      <y>260</y>
      <w>90</w>
      <h>230</h>
    </coordinates>
    <panel_attributes>lt=-&gt;
m1=0..*
m2=0..1
r2=ontvanger</panel_attributes>
    <additional_attributes>10.0;210.0;10.0;10.0</additional_attributes>
  </element>
  <element>
    <id>Relation</id>
    <coordinates>
      <x>210</x>
      <y>260</y>
      <w>70</w>
      <h>230</h>
    </coordinates>
    <panel_attributes>lt=-&gt;
m1=0..*
m2=0..1
r2=betaler</panel_attributes>
    <additional_attributes>10.0;210.0;10.0;10.0</additional_attributes>
  </element>
  <element>
    <id>Relation</id>
    <coordinates>
      <x>310</x>
      <y>670</y>
      <w>60</w>
      <h>100</h>
    </coordinates>
    <panel_attributes>lt=&lt;&lt;&lt;&lt;&lt;-&gt;
r2=lijnen
m1=1
m2=1..*
</panel_attributes>
    <additional_attributes>10.0;10.0;10.0;80.0</additional_attributes>
  </element>
  <element>
    <id>UMLClass</id>
    <coordinates>
      <x>950</x>
      <y>660</y>
      <w>180</w>
      <h>120</h>
    </coordinates>
    <panel_attributes>style=autoresize
&lt;&lt;event&gt;&gt;
ReservatieStatus
--
type:ReservatieStatusType
tijdstip: DateTime
bevestigingsCode: byte[*]
isBevestigd: boolean</panel_attributes>
    <additional_attributes/>
  </element>
  <element>
    <id>Relation</id>
    <coordinates>
      <x>600</x>
      <y>740</y>
      <w>50</w>
      <h>200</h>
    </coordinates>
    <panel_attributes>lt=-&gt;
m1=*
m2=0..1
</panel_attributes>
    <additional_attributes>10.0;180.0;10.0;10.0</additional_attributes>
  </element>
  <element>
    <id>UMLClass</id>
    <coordinates>
      <x>20</x>
      <y>1070</y>
      <w>110</w>
      <h>90</h>
    </coordinates>
    <panel_attributes>style=autoresize
&lt;&lt;value object&gt;&gt;
Periode
--
van: Datum
tot: Datum</panel_attributes>
    <additional_attributes/>
  </element>
  <element>
    <id>UMLPackage</id>
    <coordinates>
      <x>30</x>
      <y>410</y>
      <w>1190</w>
      <h>610</h>
    </coordinates>
    <panel_attributes>fg=gray
transactie</panel_attributes>
    <additional_attributes/>
  </element>
  <element>
    <id>UMLPackage</id>
    <coordinates>
      <x>30</x>
      <y>140</y>
      <w>380</w>
      <h>190</h>
    </coordinates>
    <panel_attributes>fg=gray
gebruiker</panel_attributes>
    <additional_attributes/>
  </element>
  <element>
    <id>UMLPackage</id>
    <coordinates>
      <x>10</x>
      <y>1040</y>
      <w>220</w>
      <h>130</h>
    </coordinates>
    <panel_attributes>fg=gray
util
bg=cyan</panel_attributes>
    <additional_attributes/>
  </element>
  <element>
    <id>UMLPackage</id>
    <coordinates>
      <x>420</x>
      <y>0</y>
      <w>800</w>
      <h>370</h>
    </coordinates>
    <panel_attributes>fg=gray
gereedschap</panel_attributes>
    <additional_attributes/>
  </element>
  <element>
    <id>UMLClass</id>
    <coordinates>
      <x>380</x>
      <y>920</y>
      <w>400</w>
      <h>70</h>
    </coordinates>
    <panel_attributes>style=autoresize
ReservatieTransactieLijn
--
statusType:ReservatieStatusType
reservatieTransactieType {HUUR, WAARBORG,ANNULATIE}</panel_attributes>
    <additional_attributes/>
  </element>
  <element>
    <id>UMLClass</id>
    <coordinates>
      <x>50</x>
      <y>920</y>
      <w>270</w>
      <h>70</h>
    </coordinates>
    <panel_attributes>style=autoresize
HandelTransactieLijn
--
bedrag: float 
handelsLijnType {AANKOOP,VERKOOP}</panel_attributes>
    <additional_attributes/>
  </element>
  <element>
    <id>UMLClass</id>
    <coordinates>
      <x>960</x>
      <y>830</y>
      <w>180</w>
      <h>170</h>
    </coordinates>
    <panel_attributes>style=autoresize
&lt;&lt;value object&gt;&gt;
ReservatieStatusType
--
NIEUW
GERESERVEERD
AFGEHAALD
TERUGGEBRACHT
ANNULATIE_AANBIEDER
ANNULATIE_ONTLENER
</panel_attributes>
    <additional_attributes/>
  </element>
  <element>
    <id>Relation</id>
    <coordinates>
      <x>150</x>
      <y>810</y>
      <w>210</w>
      <h>130</h>
    </coordinates>
    <panel_attributes>lt=-&gt;&gt;</panel_attributes>
    <additional_attributes>10.0;110.0;10.0;70.0;190.0;70.0;190.0;10.0</additional_attributes>
  </element>
  <element>
    <id>Relation</id>
    <coordinates>
      <x>330</x>
      <y>810</y>
      <w>110</w>
      <h>130</h>
    </coordinates>
    <panel_attributes>lt=-&gt;&gt;</panel_attributes>
    <additional_attributes>90.0;110.0;90.0;70.0;10.0;70.0;10.0;10.0</additional_attributes>
  </element>
  <element>
    <id>UMLPackage</id>
    <coordinates>
      <x>10</x>
      <y>0</y>
      <w>1310</w>
      <h>1030</h>
    </coordinates>
    <panel_attributes>fg=gray
domein
bg=green</panel_attributes>
    <additional_attributes/>
  </element>
  <element>
    <id>UMLNote</id>
    <coordinates>
      <x>510</x>
      <y>870</y>
      <w>260</w>
      <h>50</h>
    </coordinates>
    <panel_attributes>style=autoresize
bg=yellow
fg=blue
via statusType houden  we bij,
bij welke reservatiestatus deze lijn hoort</panel_attributes>
    <additional_attributes/>
  </element>
  <element>
    <id>Relation</id>
    <coordinates>
      <x>710</x>
      <y>910</y>
      <w>40</w>
      <h>30</h>
    </coordinates>
    <panel_attributes>lt=..</panel_attributes>
    <additional_attributes>10.0;10.0;17.0;10.0</additional_attributes>
  </element>
  <element>
    <id>Relation</id>
    <coordinates>
      <x>990</x>
      <y>770</y>
      <w>50</w>
      <h>80</h>
    </coordinates>
    <panel_attributes>lt=-&gt;
m1=*
m2=0..1
</panel_attributes>
    <additional_attributes>10.0;10.0;10.0;60.0</additional_attributes>
  </element>
  <element>
    <id>UMLClass</id>
    <coordinates>
      <x>1000</x>
      <y>30</y>
      <w>210</w>
      <h>110</h>
    </coordinates>
    <panel_attributes>SamengesteldGereedschap
--
-id: integer
-beschrijving: String
--
add(:Gereedschap)
remove(:Gereedschap)

</panel_attributes>
    <additional_attributes/>
  </element>
  <element>
    <id>UMLClass</id>
    <coordinates>
      <x>1000</x>
      <y>150</y>
      <w>210</w>
      <h>110</h>
    </coordinates>
    <panel_attributes>EnkelvoudigGereedschap
--
-dagPrijs: int
-waarde: int
-aankoopprijs:int
--
</panel_attributes>
    <additional_attributes/>
  </element>
  <element>
    <id>Relation</id>
    <coordinates>
      <x>920</x>
      <y>120</y>
      <w>100</w>
      <h>100</h>
    </coordinates>
    <panel_attributes>lt=&lt;&lt;-</panel_attributes>
    <additional_attributes>10.0;80.0;40.0;80.0;40.0;10.0;80.0;10.0</additional_attributes>
  </element>
  <element>
    <id>Relation</id>
    <coordinates>
      <x>920</x>
      <y>190</y>
      <w>100</w>
      <h>30</h>
    </coordinates>
    <panel_attributes>lt=&lt;&lt;-</panel_attributes>
    <additional_attributes>10.0;10.0;80.0;10.0</additional_attributes>
  </element>
  <element>
    <id>Relation</id>
    <coordinates>
      <x>790</x>
      <y>480</y>
      <w>130</w>
      <h>80</h>
    </coordinates>
    <panel_attributes>lt=-&gt;
m1=*
m2=1
</panel_attributes>
    <additional_attributes>10.0;60.0;10.0;10.0;110.0;10.0</additional_attributes>
  </element>
  <element>
    <id>UMLClass</id>
    <coordinates>
      <x>870</x>
      <y>540</y>
      <w>190</w>
      <h>50</h>
    </coordinates>
    <panel_attributes>style=autoresize
&lt;&lt;service&gt;&gt;
DefaultSharepointCalculator</panel_attributes>
    <additional_attributes/>
  </element>
  <element>
    <id>Relation</id>
    <coordinates>
      <x>960</x>
      <y>510</y>
      <w>30</w>
      <h>50</h>
    </coordinates>
    <panel_attributes>lt=&lt;&lt;.</panel_attributes>
    <additional_attributes>10.0;10.0;10.0;30.0</additional_attributes>
  </element>
  <element>
    <id>UMLClass</id>
    <coordinates>
      <x>900</x>
      <y>470</y>
      <w>150</w>
      <h>50</h>
    </coordinates>
    <panel_attributes>style=autoresize
&lt;&lt;interface&gt;&gt;
SharepointCalculator</panel_attributes>
    <additional_attributes/>
  </element>
</diagram>

**Comment by afdia** [comment]
Sorry for the late answer, this happens when you drag a relation with 2 points onto each other see #694

We will soon release 15.1 with an official bugfix, but if you don't want to wait you can load the "nightly build" from https://github.com/umlet/umlet/actions/runs/3864241138
