### ISSUE TITLE
Dead Links On Umlet Home Page umlet.com

### ISSUE THREAD

**Issue by AYColumbia** [umlet/umlet#704]
On the main page, the 2nd and 3rd links, "this one" and "here" respectively, are dead.

UMLet's design goals are also described in [this paper](http://portal.acm.org/citation.cfm?id=943259) and [this one](http://www.ifs.tuwien.ac.at/node/12586). Custom elements are described [here.](http://www.ifs.tuwien.ac.at/node/13585)

**Comment by afdia** [comment]
Thanks I will tell Martin (who maintains the website) to find out if there are alternative links or if he can host the papers on www.umlet.com

**Comment by afdia** [comment]
We now have a new website and the links have been fixed
