### ISSUE TITLE
HandlerElementMap is never cleared

### ISSUE THREAD

**Issue by ggrossetie** [umlet/umlet#711]
As a result, a long running processing, such as kroki.io, will eventually runs out of memory.

https://github.com/umlet/umlet/blob/master/umlet-swing/src/main/java/com/baselet/control/HandlerElementMap.java

Would it be possible to introduce a method to clear the HashMap on a `DiagramHandler` object?

Thanks!

**Comment by afdia** [comment]
Hi

If you just want a method to access and clear the map, I would suggest to use Java Reflection:
```java
HandlerElementMap.setHandlerForElement(null, null);
Field field = HandlerElementMap.class.getDeclaredField("gridElementToHandlerMapping");
field.setAccessible(true);
HashMap<GridElement, DiagramHandler> gridElementToHandlerMapping = (HashMap<GridElement, DiagramHandler>) field.get(null);
gridElementToHandlerMapping.clear();
```

Changing the code at this location which is referenced several 100 times at various locations is quite risky so I would avoid it for the moment.

**Comment by ggrossetie** [comment]
> Maybe you could also run Umlet batch exports as a subprocess (as described in e.g. [stackoverflow.com/questions/636367/executing-a-java-application-in-a-separate-process](https://stackoverflow.com/questions/636367/executing-a-java-application-in-a-separate-process)), then it should be guaranteed to cleanup everything (but of course the overhead would be higher I guess) and you would have the guarantee of a stable API

Yes, I've successfully created a native image of UMlet from my fork: https://github.com/yuzutech/umlet/tree/mini.
If it's something that might interest you (i.e., a CLI with a native-image produced by GraalVM), I can see how to integrate it upstream.

Cheers!

**Comment by afdia** [comment]
Thanks for the suggestion, but I would defer such a fundamental refactoring until we have the demand for that (especially because the multi-platform structure is already quite complex and hard to get into for new developers, so I would avoid further modularization for now)

**Comment by ggrossetie** [comment]
Alright, should I close this issue?

**Comment by afdia** [comment]
I will close it thanks!
