### ISSUE TITLE
update check broken and some links wrong since new website

### ISSUE THREAD

**Issue by club-mate** [umlet/umlet#713]
https://github.com/umlet/umlet/search?q=changes.htm
https://github.com/umlet/umlet/search?q=faq.htm

**Comment by afdia** [comment]
Thanks, there are even more broken links as https://github.com/umlet/umlet/search?q=.htm shows
And  the update check is also broken due to the switch from http to https

We will look into it!

**Comment by afdia** [comment]
To document the issue with the update checker:
It checks the old http website which now returns a redirect to the new one. The browser can handle it but the Java class we use doesn't
So the bugfix would be to make sure the update check handles redirects (see https://stackoverflow.com/q/1884230)
