### ISSUE TITLE
No context-sensitive help showing after pressing cmd+ space in the text panel

### ISSUE THREAD

**Issue by erixnL** [umlet/umlet#717]
Hi, I'm using Umlet 15.1 standalone software on my Macbook. When I open a new blank diagram, one box showing in the middle with several operation tips. One of them says that "Use cmd+ Space in the text panel to get context-sensitive help". I tried several times to press cmd+ space in the text panel on the right corner (also tried different elements), there is nothing showing in the text panel or any other places.

Steps to reproduce: open Umlet 15.1 on Macbook -> click "new" from the file tag -> the box showing as below image -> select any element and move mouse to the text panel on the right corner -> press cmd+space.
![image](https://github.com/umlet/umlet/assets/96608889/2bba0c51-9162-4f7e-bf32-2e4aa33fe9dd)

**Comment by afdia** [comment]
Hi, Perhaps try this:
Add any element to your diagram, click on it (now its properties are shown at the bottom right) and click at the start of any line of its properties box and now press cmd+space. It should show the commands

If you press cmd+space at any other position which is not the start of a line, it will only show the remaining options, so if you type "lt" and press it, it will show all 3 possible lt=- lt=. lt=.. but nothing else
If you press it at a line with no remaining choice, then no help will be opened

Also for the diagram properties (if the diagram and no element is selected) there is no help

If all of this doesn't work you could go to https://www.umletino.com/ and see if it works there

**Comment by erixnL** [comment]
> Hi, Perhaps try this: Add any element to your diagram, click on it (now its properties are shown at the bottom right) and click at the start of any line of its properties box and now press cmd+space. It should show the commands
> 
> If you press cmd+space at any other position which is not the start of a line, it will only show the remaining options, so if you type "lt" and press it, it will show all 3 possible lt=- lt=. lt=.. but nothing else If you press it at a line with no remaining choice, then no help will be opened
> 
> Also for the diagram properties (if the diagram and no element is selected) there is no help
> 
> If all of this doesn't work you could go to https://www.umletino.com/ and see if it works there

Thanks for the explanation. I'll try the methods you mentioned.
