### ISSUE TITLE
Properties 'bg' inconsistent result based on values

### ISSUE THREAD

**Issue by sabbir-anwar** [umlet/umlet#720]
I'm using UMLet version 15.1. properties 'bg' is not consistent with the values. I have given the bg properties value '1', it showed black background color. It doesn't show any "Invalid value" error.

Steps:
select a figure -> go to properties -> write "bg=1" 

Result:
Background of the figure becomes black

Steps:
select a figure -> go to properties -> write "bg=11111" 

Result:
Background of the figure becomes blue

**Comment by afdia** [comment]
It's true that such values doesn't make any sense, but they are possible since the beginning of Umlet, so to avoid breaking old diagrams we will leave them

Someone has to consciously write the bg=1 line so it's not that problematic
