### ISSUE TITLE
Shifted accent 

### ISSUE THREAD

**Issue by csongedip** [umlet/umlet#724]
In our language we have many upper accented characters in the ABC. For example: ÍÁÉŐÓÜÖ
I found today that in case of Á written in normal style shifts the accent a little bit to the left while writing it in bold works well. 
I tried to zoom in to max the screen and it disappeared. There are zooming steps where it is placed well and there are others when not.
I tried to export to gif and jpg. These formats keep the errorous shift.
I tried to export to svg (since its a vectorial format). It exports well.

Isn't it possible that I came accross with a font-rendering-to-pixel-graphic bug? (Sorry for presumption.)

I attached the three exports.
![new](https://github.com/umlet/umlet/assets/51206710/951d0fa0-4894-4f05-b9e5-966928ef7b3e)
![new](https://github.com/umlet/umlet/assets/51206710/9aa56910-e1a7-4c52-a9e4-e28175244a2b)
![new](https://github.com/umlet/umlet/assets/51206710/3b23a52e-098f-48b8-bb26-e892917176c3)

Thanks for your help in advance!
peter

**Comment by csongedip** [comment]
Thanx for your comprehensive testing and answer. I use UMLet over Windows what - I think - may carry different problems even if the app runs in Java VM. I tried it on Linux and I also could not detect the same problems so it can be a kind of final solution for me.
umletino is also working fine,. :-)

Oracle writes that the licensing has been changed so they recommend the newest version of JRE. I don't even find older versions for WIndows. 
Can I somehow change the fonts UMLet uses instead of changing system fonts in Windows which can lead to far?
Thanx in advance.

**Comment by afdia** [comment]
I'm not sure about Oracles Java distribution but any OpenJDK build should work with Umlet, so you could try e.g. the one (Temurin) from https://adoptium.net

Font support in Umlet is limited to what you see in File > Options, so the Default font family and an optional font to embed into the pdf export
