### ISSUE TITLE
15.1: unable to set fill colour of initial

### ISSUE THREAD

**Issue by jderijke** [umlet/umlet#727]
On the initial element it is impossible to reset the fill colour of the element.
in 15.0 I could make the circle gray by setting gray as both fg and bg.
In 15.1 I can set the border to another color, but not the fill color using the set foreground/set background menu's.

**Comment by afdia** [comment]
Thanks for the report, I guess this may be broken since implementing dark mode which changed some of the fg/bg coloring stuff
E.g. the line is still red but the initial and end state is no longer fully red
![grafik](https://github.com/umlet/umlet/assets/8770707/44b5aaab-ef6c-4e39-95fd-319f76105a1a)

**Comment by afdia** [comment]
the next version will use the fg color for the whole element. e.g. fg=red will do the following colorization

![grafik](https://github.com/user-attachments/assets/0bf849f6-ce80-4bf8-92ce-b85c93f8b29f)
