### ISSUE TITLE
How do i enable dark mode

### ISSUE THREAD

**Issue by andyy2024** [umlet/umlet#734]
Hello, i saw in the version notes that dark mode was enabled but i searched everywhere and legit dont know how to put it on. This may be a dumb question but please help.

**Comment by afdia** [comment]
Hi, in vscode you can use "umlet.theme": "Dark theme" as config
The web version uses your OS/Browser preferences (https://developer.mozilla.org/en-US/docs/Web/CSS/@media/prefers-color-scheme)

Standalone Umlet and Eclipse Plugin don't support dark mode currently

**Comment by afdia** [comment]
Standalone Umlet will also get a dark mode in the next release, see #566 for the feature request
