### ISSUE TITLE
Umlet freezes when dashed line passes through sefl

### ISSUE THREAD

**Issue by Marcusg33** [umlet/umlet#753]
# Umlet frozen when dashed line end passes through other end.

Hi, when creating a diagram I attached a line with the property `lt=.` to a box
Then when dragging one it it passed through the other and froze.
Umlet is frozen within the file editing are but not frozen in the template and properties section.
![image](https://github.com/umlet/umlet/assets/87792390/ce005d14-a982-4961-989c-b2408ba5180b)
here it has a red box where the ends met.

I was able to add something into the editing area but I can't change anything or delete the frozen line. 
'Save as.'doesn't work but as it was freezing I pressed CTRL+S and then copied that save and that works fine.
The original won't save when exiting and clicking yes to "Save changes?", nor will it exit when pressing no.
[dashed line freeze.zip](https://github.com/umlet/umlet/files/15447582/dashed.line.freeze.zip)
here's the file I saved as it was freezing

**Comment by afdia** [comment]
Hi, maybe this is issue #660?
Which Java version are you using? If it's Java8, it's probably that bug and you will have to update to Java11 or later (the distribution shouldn't matter, but https://adoptium.net/de/temurin/releases/ is widely used)

Alternatively you could also use https://www.umletino.com/umletino.html to edit your diagram which doesn't require Java and therefore has no issue.
Or if you want to use Umlet and cannot update Java for whatever reason, you remove the problematic relation using Umletino, export the fixed diagram and then proceed to work with Umlet. If you avoid dashed relation lines, the bug should not happen as far as I know

**Comment by Marcusg33** [comment]
Awesome! thanks for the help :)

**Comment by afdia** [comment]
Your welcome! I will close the issue as duplicate as we cannot fix it in our codebase
